"""add hostel and health foundation
Revision ID: 20260930_21
Revises: 20260929_20
"""
from alembic import op
import sqlalchemy as sa
revision="20260930_21";down_revision="20260929_20";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("hostels",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("tenant_id",sa.Integer(),nullable=False),sa.Column("campus_id",sa.Integer(),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("code",sa.String(60),nullable=False),sa.Column("hostel_type",sa.String(30),nullable=False,server_default="GENERAL"),sa.Column("warden_name",sa.String(120),nullable=False,server_default=""),sa.Column("warden_phone",sa.String(40),nullable=False,server_default=""),sa.Column("status",sa.String(30),nullable=False,server_default="ACTIVE"),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("tenant_id","campus_id","code",name="uq_hostel_code"))
    op.create_index("ix_hostels_tenant_id","hostels",["tenant_id"]);op.create_index("ix_hostels_campus_id","hostels",["campus_id"])
    op.create_table("hostel_rooms",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("tenant_id",sa.Integer(),nullable=False),sa.Column("campus_id",sa.Integer(),nullable=False),sa.Column("hostel_id",sa.Integer(),sa.ForeignKey("hostels.id"),nullable=False),sa.Column("room_number",sa.String(40),nullable=False),sa.Column("floor",sa.String(40),nullable=False,server_default=""),sa.Column("capacity",sa.Integer(),nullable=False,server_default="1"),sa.Column("room_type",sa.String(60),nullable=False,server_default="STANDARD"),sa.Column("status",sa.String(30),nullable=False,server_default="AVAILABLE"),sa.Column("created_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("tenant_id","hostel_id","room_number",name="uq_hostel_room"))
    for n,c in [("tenant_id","tenant_id"),("campus_id","campus_id"),("hostel_id","hostel_id")]: op.create_index("ix_hostel_rooms_"+n,"hostel_rooms",[c])
    op.create_table("hostel_allocations",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("tenant_id",sa.Integer(),nullable=False),sa.Column("campus_id",sa.Integer(),nullable=False),sa.Column("hostel_id",sa.Integer(),sa.ForeignKey("hostels.id"),nullable=False),sa.Column("room_id",sa.Integer(),sa.ForeignKey("hostel_rooms.id"),nullable=False),sa.Column("student_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("bed_number",sa.String(40),nullable=False,server_default=""),sa.Column("check_in_at",sa.DateTime(),nullable=False),sa.Column("check_out_at",sa.DateTime(),nullable=True),sa.Column("status",sa.String(30),nullable=False,server_default="ACTIVE"),sa.Column("notes",sa.Text(),nullable=False,server_default=""),sa.Column("allocated_by",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False))
    for n in ["tenant_id","campus_id","hostel_id","room_id","student_user_id"]: op.create_index("ix_hostel_allocations_"+n,"hostel_allocations",[n])
    op.create_table("health_records",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("tenant_id",sa.Integer(),nullable=False),sa.Column("campus_id",sa.Integer(),nullable=False),sa.Column("person_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("blood_group",sa.String(10),nullable=False,server_default=""),sa.Column("allergies",sa.Text(),nullable=False,server_default=""),sa.Column("medical_conditions",sa.Text(),nullable=False,server_default=""),sa.Column("emergency_contact_name",sa.String(120),nullable=False,server_default=""),sa.Column("emergency_contact_phone",sa.String(40),nullable=False,server_default=""),sa.Column("notes",sa.Text(),nullable=False,server_default=""),sa.Column("recorded_by",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False))
    for n in ["tenant_id","campus_id","person_user_id"]: op.create_index("ix_health_records_"+n,"health_records",[n])
    op.create_table("health_visits",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("tenant_id",sa.Integer(),nullable=False),sa.Column("campus_id",sa.Integer(),nullable=False),sa.Column("person_user_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("visit_type",sa.String(40),nullable=False,server_default="GENERAL"),sa.Column("complaint",sa.Text(),nullable=False),sa.Column("action_taken",sa.Text(),nullable=False,server_default=""),sa.Column("disposition",sa.String(40),nullable=False,server_default="RETURNED"),sa.Column("visited_at",sa.DateTime(),nullable=False),sa.Column("recorded_by",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(),nullable=False))
    for n in ["tenant_id","campus_id","person_user_id"]: op.create_index("ix_health_visits_"+n,"health_visits",[n])
def downgrade():
    op.drop_table("health_visits");op.drop_table("health_records");op.drop_table("hostel_allocations");op.drop_table("hostel_rooms");op.drop_table("hostels")
