import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
const TYPES=[["ENROLLMENT","Program / Grade Enrollment"],["COURSE_REGISTRATION","Course Registration"],["SECTION_ASSIGNMENT","Section / Batch Assignment"],["FACULTY_ASSIGNMENT","Faculty Assignment"],["ADVISOR_ASSIGNMENT","Advisor Assignment"]];
export default function AcademicAssignments({ui}){
 const [users,setUsers]=useState([]),[units,setUnits]=useState([]),[rows,setRows]=useState([]),[userId,setUserId]=useState(""),[unitId,setUnitId]=useState(""),[type,setType]=useState("ENROLLMENT"),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 async function load(){try{setErr("");const [u,s,a]=await Promise.all([api.get("/api/v1/users"),api.get("/api/v1/academic-structure"),api.get("/api/v1/academic-assignments")]);setUsers(u.data.filter(x=>["Student","Teacher"].includes(x.role)));setUnits(s.data);setRows(a.data)}catch(e){setErr(e?.response?.data?.detail||"Unable to load academic assignments.")}}
 useEffect(()=>{load()},[]);
 const selected=useMemo(()=>users.find(x=>x.id===Number(userId)),[users,userId]);
 const allowedUnits=useMemo(()=>{const wanted=selected?.role==="Teacher"?["COURSE","SECTION_BATCH","PROGRAM"]:["PROGRAM","ACADEMIC_PERIOD","COURSE","SECTION_BATCH"];return units.filter(x=>wanted.includes(x.unit_type))},[units,selected]);
 async function add(){try{setErr("");setMsg("");await api.post("/api/v1/academic-assignments",{user_id:Number(userId),unit_id:Number(unitId),assignment_type:type,status:"Active"});setMsg("Academic assignment saved.");setUnitId("");await load()}catch(e){setErr(e?.response?.data?.detail||"Unable to save assignment.")}}
 async function remove(id){if(!window.confirm("Remove this assignment?"))return;try{await api.delete("/api/v1/academic-assignments/"+id);setMsg("Assignment removed.");await load()}catch(e){setErr(e?.response?.data?.detail||"Unable to remove assignment.")}}
 return <div><section className="role-hero"><div><span className="eyebrow">{ui.label} Academic Operations</span><h1>Enrollment & Faculty Assignment</h1><p>Connect students and faculty to the academic structure configured for this institution.</p></div><div className="hero-badge">{rows.length} Links</div></section>
 <div className="setup-grid"><section className="panel"><div className="panel-title"><b>Create Assignment</b><span>RBAC controlled</span></div><div className="setup-form">
 <label>Student / Faculty<select value={userId} onChange={e=>{setUserId(e.target.value);setUnitId("")}}><option value="">Select user</option>{users.map(x=><option value={x.id} key={x.id}>{x.name} — {x.role}</option>)}</select></label>
 <label>Assignment Type<select value={type} onChange={e=>setType(e.target.value)}>{TYPES.filter(([v])=>selected?.role==="Teacher"?["FACULTY_ASSIGNMENT","ADVISOR_ASSIGNMENT"].includes(v):!["FACULTY_ASSIGNMENT","ADVISOR_ASSIGNMENT"].includes(v)).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>
 <label>Academic Unit<select value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="">Select academic unit</option>{allowedUnits.map(x=><option value={x.id} key={x.id}>{x.name} — {x.code}</option>)}</select></label>
 </div>{err&&<div className="error">{err}</div>}{msg&&<div className="success-message">{msg}</div>}<button className="primary" disabled={!userId||!unitId} onClick={add}>Assign</button></section>
 <section className="panel"><div className="panel-title"><b>Operational Flow</b><span>{ui.label}</span></div><div className="structure-flow"><span>Student Admission / Faculty</span><b>↓</b><span>Program / Grade</span><b>↓</b><span>Academic Period</span><b>↓</b><span>Course</span><b>↓</b><span>Section / Batch</span></div></section></div>
 <section className="panel structure-table"><div className="panel-title"><b>Current Assignments</b><span>{rows.length} records</span></div><div className="table-scroll"><table><thead><tr><th>User</th><th>Role</th><th>Assignment</th><th>Academic Unit</th><th>Type</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan="7" className="empty-cell">No assignments configured.</td></tr>:rows.map(r=><tr key={r.id}><td><b>{r.user_name}</b></td><td>{r.user_role}</td><td>{r.assignment_type.replaceAll("_"," ")}</td><td>{r.unit_name}</td><td>{r.unit_type.replaceAll("_"," ")}</td><td>{r.status}</td><td><button className="table-action danger" onClick={()=>remove(r.id)}>Remove</button></td></tr>)}</tbody></table></div></section></div>
}
