import React,{useEffect,useState} from "react"; import {api} from "../api";
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
export default function AccountsFinance({title,ui}){
 const [rows,setRows]=useState([]),[receipts,setReceipts]=useState([]),[err,setErr]=useState(""),[msg,setMsg]=useState("");
 const [fee,setFee]=useState({student_user_id:"",fee_code:"",title:"",amount_due:"",due_at:""});
 const [payment,setPayment]=useState({ledger_id:"",amount:"",reference:""});
 const load=()=>api.get("/api/v1/fee-ledger").then(r=>setRows(r.data)).catch(e=>setErr(e?.response?.data?.detail||"Unable to load fee ledger."));
 useEffect(()=>{load()},[]);
 const setF=(k,v)=>setFee(x=>({...x,[k]:v})),setP=(k,v)=>setPayment(x=>({...x,[k]:v}));
 async function assignFee(){try{await api.post("/api/v1/fee-ledger",{student_user_id:Number(fee.student_user_id),fee_code:fee.fee_code,title:fee.title,amount_due:Number(fee.amount_due),due_at:fee.due_at||null});setFee({student_user_id:"",fee_code:"",title:"",amount_due:"",due_at:""});setMsg("Fee assigned successfully.");setErr("");load()}catch(e){setErr(e?.response?.data?.detail||"Unable to assign fee.")}}
 async function recordPayment(){try{const r=await api.post("/api/v1/fee-ledger/"+payment.ledger_id+"/payments",{amount:Number(payment.amount),reference:payment.reference});setPayment({ledger_id:"",amount:"",reference:""});setMsg("Payment recorded. Receipt: "+r.data.receipt_no);setErr("");load()}catch(e){setErr(e?.response?.data?.detail||"Unable to record payment.")}}
 async function receiptsFor(id){try{const r=await api.get("/api/v1/fee-ledger/"+id+"/receipts");setReceipts(r.data);setErr("")}catch(e){setErr(e?.response?.data?.detail||"Unable to load receipts.")}}
 const due=rows.reduce((s,r)=>s+r.amount_due,0),paid=rows.reduce((s,r)=>s+r.amount_paid,0),balance=rows.reduce((s,r)=>s+r.balance,0);
 const feeValid=Number(fee.student_user_id)>0&&fee.fee_code.trim()&&fee.title.trim()&&Number(fee.amount_due)>0;
 const selected=rows.find(r=>String(r.id)===String(payment.ledger_id)); const payValid=selected&&Number(payment.amount)>0&&Number(payment.amount)<=selected.balance;
 return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Accounts</span><h1>{title}</h1><p>Assign student fees, record verified offline/bank payments and review receipts.</p></div></section>{err&&<div className="error">{err}</div>}{msg&&<div className="panel"><p>{msg}</p></div>}
 <div className="finance-kpis"><article><small>Assigned</small><strong>{money(due)}</strong></article><article><small>Collected</small><strong>{money(paid)}</strong></article><article><small>Outstanding</small><strong>{money(balance)}</strong></article></div>
 {title==="Fees"&&<section className="panel"><div className="panel-title"><b>Assign Fee</b><span>Student ledger</span></div><div className="setup-form"><label>Student User ID<input type="number" min="1" value={fee.student_user_id} onChange={e=>setF("student_user_id",e.target.value)}/></label><label>Fee Code<input value={fee.fee_code} onChange={e=>setF("fee_code",e.target.value)}/></label><label>Description<input value={fee.title} onChange={e=>setF("title",e.target.value)}/></label><label>Amount Due<input type="number" min="0.01" step="0.01" value={fee.amount_due} onChange={e=>setF("amount_due",e.target.value)}/></label><label>Due Date<input type="datetime-local" value={fee.due_at} onChange={e=>setF("due_at",e.target.value)}/></label></div><button className="primary" disabled={!feeValid} onClick={assignFee}>Assign Fee</button></section>}
 {title==="Payments"&&<section className="panel"><div className="panel-title"><b>Record Payment</b><span>Offline / bank verified payment</span></div><div className="setup-form"><label>Fee Ledger<select value={payment.ledger_id} onChange={e=>setP("ledger_id",e.target.value)}><option value="">Select outstanding fee</option>{rows.filter(r=>r.balance>0).map(r=><option key={r.id} value={r.id}>{r.fee_code} · Student {r.student_user_id} · Balance {money(r.balance)}</option>)}</select></label><label>Amount<input type="number" min="0.01" step="0.01" max={selected?.balance||undefined} value={payment.amount} onChange={e=>setP("amount",e.target.value)}/></label><label>Bank / Transaction Reference<input value={payment.reference} onChange={e=>setP("reference",e.target.value)}/></label></div><button className="primary" disabled={!payValid} onClick={recordPayment}>Record Payment & Generate Receipt</button></section>}
 <section className="panel structure-table"><div className="table-scroll"><table><thead><tr><th>Fee Code</th><th>Student ID</th><th>Description</th><th>Due</th><th>Paid</th><th>Balance</th><th>Status</th><th></th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{r.fee_code}</td><td>{r.student_user_id}</td><td><b>{r.title}</b></td><td>{money(r.amount_due)}</td><td>{money(r.amount_paid)}</td><td>{money(r.balance)}</td><td>{r.status}</td><td><button className="table-action" onClick={()=>receiptsFor(r.id)}>Receipts</button></td></tr>):<tr><td colSpan="8" className="empty-cell">No fee ledger entries available.</td></tr>}</tbody></table></div></section>
 {(title==="Receipts"||receipts.length>0)&&<section className="panel structure-table"><div className="panel-title"><b>Receipt History</b><span>{receipts.length} loaded</span></div><div className="table-scroll"><table><thead><tr><th>Receipt</th><th>Amount</th><th>Reference</th><th>Paid At</th></tr></thead><tbody>{receipts.length?receipts.map(x=><tr key={x.id}><td>{x.receipt_no}</td><td>{money(x.amount)}</td><td>{x.reference||"—"}</td><td>{new Date(x.paid_at).toLocaleString()}</td></tr>):<tr><td colSpan="4" className="empty-cell">Choose Receipts on a fee ledger entry to view its payment history.</td></tr>}</tbody></table></div></section>}</div>
}