import React,{useEffect,useState} from "react"; import {api} from "../api";
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
export default function AccountsFinance({title,ui}){
 const [rows,setRows]=useState([]),[receipts,setReceipts]=useState([]),[students,setStudents]=useState([]),[payments,setPayments]=useState([]),[summary,setSummary]=useState(null),[report,setReport]=useState(null),[dates,setDates]=useState({start:"",end:""}),[studentSearch,setStudentSearch]=useState(""),[err,setErr]=useState(""),[msg,setMsg]=useState("");
 const [fee,setFee]=useState({student_user_id:"",fee_code:"",title:"",amount_due:"",due_at:""});
 const [payment,setPayment]=useState({ledger_id:"",amount:"",reference:""});
 const load=()=>Promise.all([api.get("/api/v1/fee-ledger"),api.get("/api/v1/finance/summary")]).then(([r,s])=>{setRows(r.data);setSummary(s.data)}).catch(e=>setErr(e?.response?.data?.detail||"Unable to load finance data."));
 useEffect(()=>{load();api.get("/api/v1/finance/students").then(r=>setStudents(r.data)).catch(()=>{});api.get("/api/v1/finance/payments").then(r=>setPayments(r.data)).catch(()=>{})},[]);
 const setF=(k,v)=>setFee(x=>({...x,[k]:v})),setP=(k,v)=>setPayment(x=>({...x,[k]:v}));
 async function assignFee(){try{await api.post("/api/v1/fee-ledger",{student_user_id:Number(fee.student_user_id),fee_code:fee.fee_code,title:fee.title,amount_due:Number(fee.amount_due),due_at:fee.due_at||null});setFee({student_user_id:"",fee_code:"",title:"",amount_due:"",due_at:""});setMsg("Fee assigned successfully.");setErr("");load()}catch(e){setErr(e?.response?.data?.detail||"Unable to assign fee.")}}
 async function recordPayment(){try{const r=await api.post("/api/v1/fee-ledger/"+payment.ledger_id+"/payments",{amount:Number(payment.amount),reference:payment.reference});setPayment({ledger_id:"",amount:"",reference:""});setMsg("Payment recorded. Receipt: "+r.data.receipt_no);setErr("");load();api.get("/api/v1/finance/payments").then(x=>setPayments(x.data))}catch(e){setErr(e?.response?.data?.detail||"Unable to record payment.")}}
 async function cancelFee(id){if(!window.confirm("Cancel this unpaid fee assignment?"))return;try{await api.post("/api/v1/fee-ledger/"+id+"/cancel");setMsg("Fee assignment cancelled.");setErr("");load()}catch(e){setErr(e?.response?.data?.detail||"Unable to cancel fee.")}}
 async function receiptsFor(id){try{const r=await api.get("/api/v1/fee-ledger/"+id+"/receipts");setReceipts(r.data);setErr("")}catch(e){setErr(e?.response?.data?.detail||"Unable to load receipts.")}}
 async function runReport(){try{const q=new URLSearchParams();if(dates.start)q.set("start_date",dates.start);if(dates.end)q.set("end_date",dates.end);const r=await api.get("/api/v1/finance/report?"+q.toString());setReport(r.data);setErr("")}catch(e){setErr(e?.response?.data?.detail||"Unable to generate finance report.")}}
 function exportCsv(){if(!report)return;const head=["Receipt","Student ID","Student","Email","Fee Code","Fee","Amount","Reference","Paid At"];const esc=v=>{let s=String(v??"");if(/^[=+@-]/.test(s))s="\'"+s;return '"'+s.replaceAll('"','""')+'"'};const lines=[head,...report.payments.map(x=>[x.receipt_no,x.student_id,x.student_name,x.student_email,x.fee_code,x.fee_title,x.amount,x.reference,x.paid_at])].map(r=>r.map(esc).join(",")).join("\\n");const blob=new Blob([lines],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="gaint-finance-report.csv";a.click();URL.revokeObjectURL(a.href)}
 const due=rows.reduce((s,r)=>s+r.amount_due,0),paid=rows.reduce((s,r)=>s+r.amount_paid,0),balance=rows.reduce((s,r)=>s+r.balance,0);
 const feeValid=Number(fee.student_user_id)>0&&fee.fee_code.trim()&&fee.title.trim()&&Number(fee.amount_due)>0;
 const selected=rows.find(r=>String(r.id)===String(payment.ledger_id)); const payValid=selected&&Number(payment.amount)>0&&Number(payment.amount)<=selected.balance;
 return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Accounts</span><h1>{title}</h1><p>Assign student fees, record verified offline/bank payments and review receipts.</p></div></section>{err&&<div className="error">{err}</div>}{msg&&<div className="panel"><p>{msg}</p></div>}
 <div className="finance-kpis"><article><small>Assigned</small><strong>{money(summary?.assigned??due)}</strong></article><article><small>Collected</small><strong>{money(summary?.collected??paid)}</strong></article><article><small>Outstanding</small><strong>{money(summary?.outstanding??balance)}</strong></article><article><small>Paid / Partial / Due</small><strong>{summary?`${summary.paid_count} / ${summary.partial_count} / ${summary.due_count}`:"—"}</strong></article></div>
 {title==="Finance Reports"&&<><section className="panel"><div className="panel-title"><b>Finance Report</b><span>Date-filtered collections</span></div><div className="setup-form"><label>From<input type="date" value={dates.start} onChange={e=>setDates(x=>({...x,start:e.target.value}))}/></label><label>To<input type="date" value={dates.end} onChange={e=>setDates(x=>({...x,end:e.target.value}))}/></label></div><button className="primary" onClick={runReport}>Generate Report</button>{report&&<button className="secondary" onClick={exportCsv}>Export CSV</button>}</section>{report&&<section className="panel structure-table"><div className="finance-kpis"><article><small>Payments</small><strong>{report.payment_count}</strong></article><article><small>Collected</small><strong>{money(report.total_collected)}</strong></article></div><div className="table-scroll"><table><thead><tr><th>Receipt</th><th>Student</th><th>Fee</th><th>Amount</th><th>Reference</th><th>Paid At</th></tr></thead><tbody>{report.payments.length?report.payments.map(x=><tr key={x.receipt_no}><td>{x.receipt_no}</td><td>{x.student_name}<br/><small>{x.student_email}</small></td><td>{x.fee_title}<br/><small>{x.fee_code}</small></td><td>{money(x.amount)}</td><td>{x.reference||"—"}</td><td>{new Date(x.paid_at).toLocaleString()}</td></tr>):<tr><td colSpan="6" className="empty-cell">No payments in the selected period.</td></tr>}</tbody></table></div></section>}</>}
 {title==="Fees"&&<section className="panel"><div className="panel-title"><b>Assign Fee</b><span>Student ledger</span></div><div className="setup-form"><label>Student<input placeholder="Search student name or email" value={studentSearch} onChange={e=>setStudentSearch(e.target.value)}/><select value={fee.student_user_id} onChange={e=>setF("student_user_id",e.target.value)}><option value="">Select student</option>{students.filter(s=>(s.name+" "+s.email).toLowerCase().includes(studentSearch.toLowerCase())).map(s=><option key={s.id} value={s.id}>{s.name} — {s.email}</option>)}</select></label><label>Fee Code<input value={fee.fee_code} onChange={e=>setF("fee_code",e.target.value)}/></label><label>Description<input value={fee.title} onChange={e=>setF("title",e.target.value)}/></label><label>Amount Due<input type="number" min="0.01" step="0.01" value={fee.amount_due} onChange={e=>setF("amount_due",e.target.value)}/></label><label>Due Date<input type="datetime-local" value={fee.due_at} onChange={e=>setF("due_at",e.target.value)}/></label></div><button className="primary" disabled={!feeValid} onClick={assignFee}>Assign Fee</button></section>}
 {title==="Payments"&&<section className="panel"><div className="panel-title"><b>Record Payment</b><span>Offline / bank verified payment</span></div><div className="setup-form"><label>Fee Ledger<select value={payment.ledger_id} onChange={e=>setP("ledger_id",e.target.value)}><option value="">Select outstanding fee</option>{rows.filter(r=>r.balance>0).map(r=><option key={r.id} value={r.id}>{r.fee_code} · {students.find(s=>s.id===r.student_user_id)?.name||("Student "+r.student_user_id)} · Balance {money(r.balance)}</option>)}</select></label><label>Amount<input type="number" min="0.01" step="0.01" max={selected?.balance||undefined} value={payment.amount} onChange={e=>setP("amount",e.target.value)}/></label><label>Bank / Transaction Reference<input value={payment.reference} onChange={e=>setP("reference",e.target.value)}/></label></div><button className="primary" disabled={!payValid} onClick={recordPayment}>Record Payment & Generate Receipt</button></section>}
 <section className="panel structure-table"><div className="table-scroll"><table><thead><tr><th>Fee Code</th><th>Student</th><th>Description</th><th>Due</th><th>Paid</th><th>Balance</th><th>Status</th><th></th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{r.fee_code}</td><td>{students.find(s=>s.id===r.student_user_id)?.name||("Student "+r.student_user_id)}<br/><small>{students.find(s=>s.id===r.student_user_id)?.email||("ID "+r.student_user_id)}</small></td><td><b>{r.title}</b></td><td>{money(r.amount_due)}</td><td>{money(r.amount_paid)}</td><td>{money(r.balance)}</td><td>{r.status}</td><td><button className="table-action" onClick={()=>receiptsFor(r.id)}>Receipts</button>{r.status!=="CANCELLED"&&r.amount_paid===0&&<button className="table-action" onClick={()=>cancelFee(r.id)}>Cancel</button>}</td></tr>):<tr><td colSpan="8" className="empty-cell">No fee ledger entries available.</td></tr>}</tbody></table></div></section>
 {title==="Receipts"&&<section className="panel structure-table"><div className="panel-title"><b>Institution Payment History</b><span>{payments.length} payments</span></div><div className="table-scroll"><table><thead><tr><th>Receipt</th><th>Student</th><th>Fee</th><th>Amount</th><th>Reference</th><th>Paid At</th></tr></thead><tbody>{payments.length?payments.map(x=><tr key={x.id}><td>{x.receipt_no}</td><td><b>{x.student_name}</b><br/><small>ID {x.student_user_id}</small></td><td>{x.fee_title}<br/><small>{x.fee_code}</small></td><td>{money(x.amount)}</td><td>{x.reference||"—"}</td><td>{new Date(x.paid_at).toLocaleString()}</td></tr>):<tr><td colSpan="6" className="empty-cell">No payments have been recorded.</td></tr>}</tbody></table></div></section>}
 {(title!=="Receipts"&&receipts.length>0)&&<section className="panel structure-table"><div className="panel-title"><b>Receipt History</b><span>{receipts.length} loaded</span></div><div className="table-scroll"><table><thead><tr><th>Receipt</th><th>Amount</th><th>Reference</th><th>Paid At</th></tr></thead><tbody>{receipts.length?receipts.map(x=><tr key={x.id}><td>{x.receipt_no}</td><td>{money(x.amount)}</td><td>{x.reference||"—"}</td><td>{new Date(x.paid_at).toLocaleString()}</td></tr>):<tr><td colSpan="4" className="empty-cell">Choose Receipts on a fee ledger entry to view its payment history.</td></tr>}</tbody></table></div></section>}</div>
}