import React,{useEffect,useState} from "react"; import {api} from "../api";
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
export default function AccountsFinance({title,ui}){
 const [rows,setRows]=useState([]),[receipts,setReceipts]=useState([]),[err,setErr]=useState("");
 const load=()=>api.get("/api/v1/fee-ledger").then(r=>setRows(r.data)).catch(e=>setErr(e?.response?.data?.detail||"Unable to load fee ledger."));
 useEffect(()=>{load()},[]);
 async function receiptsFor(id){try{const r=await api.get("/api/v1/fee-ledger/"+id+"/receipts");setReceipts(r.data);setErr("")}catch(e){setErr(e?.response?.data?.detail||"Unable to load receipts.")}}
 const due=rows.reduce((s,r)=>s+r.amount_due,0),paid=rows.reduce((s,r)=>s+r.amount_paid,0),balance=rows.reduce((s,r)=>s+r.balance,0);
 return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Accounts</span><h1>{title}</h1><p>Shared student fee ledger used by Accounts, Students and Parents.</p></div></section>{err&&<div className="error">{err}</div>}<div className="finance-kpis"><article><small>Assigned</small><strong>{money(due)}</strong></article><article><small>Collected</small><strong>{money(paid)}</strong></article><article><small>Outstanding</small><strong>{money(balance)}</strong></article></div><section className="panel structure-table"><div className="table-scroll"><table><thead><tr><th>Fee Code</th><th>Student ID</th><th>Description</th><th>Due</th><th>Paid</th><th>Balance</th><th>Status</th><th></th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{r.fee_code}</td><td>{r.student_user_id}</td><td><b>{r.title}</b></td><td>{money(r.amount_due)}</td><td>{money(r.amount_paid)}</td><td>{money(r.balance)}</td><td>{r.status}</td><td><button className="table-action" onClick={()=>receiptsFor(r.id)}>Receipts</button></td></tr>):<tr><td colSpan="8" className="empty-cell">No fee ledger entries available.</td></tr>}</tbody></table></div></section>{receipts.length>0&&<section className="panel structure-table"><div className="panel-title"><b>Receipt History</b></div><div className="table-scroll"><table><thead><tr><th>Receipt</th><th>Amount</th><th>Reference</th><th>Paid At</th></tr></thead><tbody>{receipts.map(x=><tr key={x.id}><td>{x.receipt_no}</td><td>{money(x.amount)}</td><td>{x.reference||"—"}</td><td>{new Date(x.paid_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>}</div>
}