import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
const pretty=s=>String(s||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function AdminAcademics({ui}){
 const terms=ui.label==="School"?{desc:"School-wide academic hierarchy across academic years, classes, grades, sections and subjects.",units:"Classes / Grades",programs:"Academic Years / Terms",courses:"Subjects",sections:"Sections",learners:"Assigned Pupils",staff:"Assigned Teachers",learnerLower:"pupil(s)",staffLower:"teacher(s)",catalogue:"School Academic Catalogue",add:"Add School Academic Unit"}:ui.label==="College"?{desc:"College-wide academic hierarchy across departments, programs, semesters, sections and courses.",units:"Departments / Programs",programs:"Programs",courses:"Courses",sections:"Sections / Batches",learners:"Assigned Students",staff:"Assigned Faculty / Teachers",learnerLower:"student(s)",staffLower:"faculty / teacher(s)",catalogue:"College Academic Catalogue",add:"Add College Academic Unit"}:{desc:"University-wide academic hierarchy across faculties, departments, programs, regulations, semesters and courses.",units:"Faculties / Departments",programs:"Programs",courses:"Courses",sections:"Cohorts / Sections",learners:"Assigned Students",staff:"Assigned Faculty / Teachers",learnerLower:"student(s)",staffLower:"faculty / teacher(s)",catalogue:"University Academic Catalogue",add:"Add University Academic Unit"};
 const[data,setData]=useState(null),[error,setError]=useState(""),[type,setType]=useState("ALL"),[query,setQuery]=useState(""),[form,setForm]=useState({unit_type:"CAMPUS",name:"",code:"",parent_id:"",campus_id:"1",status:"Active"}),[editForm,setEditForm]=useState(null),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 const load=()=>api.get("/api/v1/admin/academics-overview").then(r=>{setData(r.data);setError("")}).catch(e=>setError(e?.response?.data?.detail||"Unable to load academics."));
 useEffect(()=>{load()},[]); const addUnit=async e=>{e.preventDefault();try{setSaving(true);setError("");setMessage("");await api.post("/api/v1/academic-structure",{...form,name:form.name.trim(),code:form.code.trim(),campus_id:Number(form.campus_id),parent_id:form.parent_id?Number(form.parent_id):null});setForm({unit_type:"CAMPUS",name:"",code:"",parent_id:"",campus_id:"1",status:"Active"});setMessage("Academic unit added successfully.");await load()}catch(e){setError(e?.response?.data?.detail||"Unable to add academic unit.")}finally{setSaving(false)}}; const editUnit=x=>{setError("");setMessage("");setEditForm({id:x.id,unit_type:x.unit_type,name:x.name,code:x.code,parent_id:x.parent_id??"",campus_id:String(x.campus_id),status:x.status})}; const saveUnit=async e=>{e.preventDefault();try{setSaving(true);setError("");await api.put("/api/v1/academic-structure/"+editForm.id,{unit_type:editForm.unit_type,name:editForm.name.trim(),code:editForm.code.trim(),parent_id:editForm.parent_id?Number(editForm.parent_id):null,campus_id:Number(editForm.campus_id),status:editForm.status});setEditForm(null);setMessage("Academic unit updated successfully.");await load()}catch(e){setError(e?.response?.data?.detail||"Unable to update academic unit.")}finally{setSaving(false)}};
 const types=useMemo(()=>data?Object.keys(data.type_counts).sort():[],[data]);
 const rows=useMemo(()=>{if(!data)return[];const q=query.trim().toLowerCase();return data.units.filter(x=>(type==="ALL"||x.unit_type===type)&&(!q||[x.name,x.code,x.parent,x.unit_type].some(v=>String(v).toLowerCase().includes(q))))},[data,type,query]);
 return <div>
  <section className="module-context"><div><span className="eyebrow">{ui.label} • Institution Admin</span><h1>Academics</h1><p>{terms.desc}</p></div></section>
  {error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}
  {data&&<>
   <div className="module-kpis"><article><small>{terms.units}</small><strong>{data.summary.units}</strong></article><article><small>{terms.programs}</small><strong>{data.summary.programs}</strong></article><article><small>{terms.courses}</small><strong>{data.summary.courses}</strong></article><article><small>{terms.sections}</small><strong>{data.summary.sections}</strong></article><article><small>{terms.learners}</small><strong>{data.summary.assigned_students}</strong></article><article><small>{terms.staff}</small><strong>{data.summary.assigned_teachers}</strong></article></div>
   {(data.summary.unassigned_students>0||data.summary.unassigned_teachers>0)&&<section className="panel"><div className="panel-title"><b>Assignment Attention</b><span>Action required</span></div><p>{data.summary.unassigned_students} {terms.learnerLower} and {data.summary.unassigned_teachers} {terms.staffLower} currently have no active academic assignment. Use <b>Enrollment & Assignments</b> to connect them.</p></section>}
   <section className="panel"><div className="panel-title"><b>{terms.add}</b><span>Build the hierarchy from Campus downward</span></div><form className="form-grid" onSubmit={addUnit}><select value={form.unit_type} onChange={e=>setForm({...form,unit_type:e.target.value,parent_id:""})}>{["CAMPUS","SCHOOL_FACULTY","DEPARTMENT","PROGRAM","ACADEMIC_PERIOD","COURSE","SECTION_BATCH"].map(x=><option key={x} value={x}>{pretty(x)}</option>)}</select><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Unit name"/><input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="Unique code"/><input required type="number" min="1" value={form.campus_id} onChange={e=>setForm({...form,campus_id:e.target.value})} placeholder="Campus ID"/>{form.unit_type!=="CAMPUS"&&<select required value={form.parent_id} onChange={e=>setForm({...form,parent_id:e.target.value})}><option value="">Select parent</option>{data.units.map(x=><option key={x.id} value={x.id}>{pretty(x.unit_type)} — {x.name}</option>)}</select>}<button disabled={saving}>{saving?"Saving...":"Add Academic Unit"}</button></form></section>
   {editForm&&<section className="panel"><div className="panel-title"><b>Update Academic Unit</b><button type="button" className="table-action" onClick={()=>setEditForm(null)}>Cancel</button></div><form className="form-grid" onSubmit={saveUnit}><label>Type<select value={editForm.unit_type} onChange={e=>setEditForm(x=>({...x,unit_type:e.target.value,parent_id:e.target.value==="CAMPUS"?"":x.parent_id}))}>{["CAMPUS","SCHOOL_FACULTY","DEPARTMENT","PROGRAM","ACADEMIC_PERIOD","COURSE","SECTION_BATCH"].map(x=><option key={x} value={x}>{pretty(x)}</option>)}</select></label><label>Name<input required minLength="2" value={editForm.name} onChange={e=>setEditForm(x=>({...x,name:e.target.value}))}/></label><label>Code<input required minLength="1" value={editForm.code} onChange={e=>setEditForm(x=>({...x,code:e.target.value}))}/></label><label>Campus ID<input required type="number" min="1" value={editForm.campus_id} onChange={e=>setEditForm(x=>({...x,campus_id:e.target.value}))}/></label>{editForm.unit_type!=="CAMPUS"&&<label>Parent<select required value={editForm.parent_id} onChange={e=>setEditForm(x=>({...x,parent_id:e.target.value}))}><option value="">Select parent</option>{data.units.filter(x=>x.id!==editForm.id).map(x=><option key={x.id} value={x.id}>{pretty(x.unit_type)} — {x.name}</option>)}</select></label>}<label>Status<select value={editForm.status} onChange={e=>setEditForm(x=>({...x,status:e.target.value}))}><option>Active</option><option>Inactive</option></select></label><button disabled={saving}>{saving?"Saving...":"Save Changes"}</button></form></section>}
   <section className="panel structure-table"><div className="panel-title"><b>{terms.catalogue}</b><span>{rows.length} visible units</span></div>
    <div className="form-grid"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, code or parent..." /><select value={type} onChange={e=>setType(e.target.value)}><option value="ALL">All unit types</option>{types.map(x=><option key={x} value={x}>{pretty(x)}</option>)}</select></div>
    <div className="table-scroll"><table><thead><tr><th>Type</th><th>Name</th><th>Code</th><th>Parent</th><th>{terms.learners.replace("Assigned ","")}</th><th>{terms.staff.replace("Assigned ","")}</th><th>Links</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td>{pretty(x.unit_type)}</td><td><b>{x.name}</b></td><td>{x.code}</td><td>{x.parent}</td><td>{x.students}</td><td>{x.teachers}</td><td>{x.assignments}</td><td>{x.status}</td><td><button type="button" onClick={()=>editUnit(x)}>Update</button></td></tr>):<tr><td colSpan="9" className="empty-cell">No academic units match these filters.</td></tr>}</tbody></table></div>
   </section>
  </>}
 </div>
}
