import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";

export default function AdminStudents(){
 const [rows,setRows]=useState([]),[query,setQuery]=useState(""),[status,setStatus]=useState("ALL"),[profile,setProfile]=useState(null),[history,setHistory]=useState([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[editing,setEditing]=useState(null);
 const load=()=>api.get("/api/v1/admissions/students").then(r=>setRows(r.data)).catch(e=>setError(e?.response?.data?.detail||"Unable to load students."));
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>rows.filter(s=>{const q=(s.name+" "+s.email).toLowerCase().includes(query.toLowerCase());return q&&(status==="ALL"||s.status.toUpperCase()===status)}),[rows,query,status]);
 async function saveStudent(e){e.preventDefault();try{setError("");await api.patch("/api/v1/admin/students/"+editing.id,{name:editing.name,email:editing.email,campus_id:Number(editing.campus_id)});setMessage("Student details updated.");setEditing(null);await load()}catch(e){setError(e?.response?.data?.detail||"Unable to update student.")}}
 async function toggleStatus(s){const activate=s.status!=="Active";if(!activate&&!window.confirm("Deactivate this student?"))return;try{setError("");await api.patch("/api/v1/admin/students/"+s.id,{is_active:activate});setMessage(activate?"Student reactivated.":"Student deactivated.");await load()}catch(e){setError(e?.response?.data?.detail||"Unable to change student status.")}}
 async function openProfile(s){try{setError("");const [p,h]=await Promise.all([api.get("/api/v1/admissions/students/"+s.id+"/profile"),api.get("/api/v1/admissions/students/"+s.id+"/history")]);setProfile(p.data);setHistory(h.data)}catch(e){setError(e?.response?.data?.detail||"Unable to load student details.")}}
 return <div className="workspace-page"><div className="page-heading"><div><span className="eyebrow">Institution Administration</span><h1>Students</h1><p>Institution student directory, enrollment and guardian overview.</p></div></div>{error&&<div className="error-banner">{error}</div>}{message&&<div className="success-banner">{message}</div>}
 <section className="kpi-grid"><div className="kpi-card"><small>Total</small><strong>{rows.length}</strong></div><div className="kpi-card"><small>Active</small><strong>{rows.filter(x=>x.status==="Active").length}</strong></div><div className="kpi-card"><small>Withdrawn</small><strong>{rows.filter(x=>x.status==="Withdrawn").length}</strong></div><div className="kpi-card"><small>Without Guardian</small><strong>{rows.filter(x=>!x.has_guardian).length}</strong></div></section>
 <section className="panel"><div className="panel-title"><b>Student Directory</b><span>{filtered.length} shown</span></div><div className="toolbar"><input className="search-input" placeholder="Search name or email" value={query} onChange={e=>setQuery(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All status</option><option value="ACTIVE">Active</option><option value="WITHDRAWN">Withdrawn</option></select></div><div className="table-scroll"><table><thead><tr><th>Student</th><th>Academic Assignment</th><th>Section / Batch</th><th>Guardian</th><th>Status</th><th>Actions</th><th>Details</th></tr></thead><tbody>{filtered.length?filtered.map(s=><tr key={s.id}><td><strong>{s.name}</strong><br/><small>{s.email}</small></td><td>{s.assignments.filter(a=>a.assignment_type!=="SECTION_ASSIGNMENT").map(a=><div key={a.id}>{a.unit_name}</div>)}</td><td>{s.assignments.find(a=>a.assignment_type==="SECTION_ASSIGNMENT")?.unit_name||"Not assigned"}</td><td>{s.has_guardian?"Linked":"Not linked"}</td><td>{s.status}</td><td><button className="table-action" onClick={()=>setEditing({id:s.id,name:s.name,email:s.email,campus_id:s.campus_id})}>Edit</button> <button className="table-action" onClick={()=>toggleStatus(s)}>{s.status==="Active"?"Deactivate":"Reactivate"}</button></td><td><button className="table-action" onClick={()=>openProfile(s)}>View Student</button></td></tr>):<tr><td colSpan="7" className="empty-cell">No students found.</td></tr>}</tbody></table></div></section>
 {editing&&<section className="panel"><div className="panel-title"><b>Edit Student</b><button className="table-action" onClick={()=>setEditing(null)}>Cancel</button></div><form className="setup-form" onSubmit={saveStudent}><label>Name<input required value={editing.name} onChange={e=>setEditing(x=>({...x,name:e.target.value}))}/></label><label>Email<input required type="email" value={editing.email} onChange={e=>setEditing(x=>({...x,email:e.target.value}))}/></label><label>Campus ID<input required type="number" min="1" value={editing.campus_id} onChange={e=>setEditing(x=>({...x,campus_id:e.target.value}))}/></label><button className="primary">Save Changes</button></form></section>}
 {profile&&<section className="panel"><div className="panel-title"><b>{profile.name} — Student Details</b><button className="table-action" onClick={()=>{setProfile(null);setHistory([])}}>Close</button></div><div className="detail-grid"><div><small>Email</small><strong>{profile.email}</strong></div><div><small>Campus</small><strong>{profile.campus_id}</strong></div><div><small>Status</small><strong>{profile.status}</strong></div><div><small>History Events</small><strong>{profile.history_count}</strong></div><div><small>Academic Enrollment</small>{profile.academics.length?profile.academics.map((a,i)=><div key={i}><strong>{a.unit_name}</strong><br/><small>{a.assignment_type.replaceAll("_"," ")}</small></div>):<strong>Not assigned</strong>}</div><div><small>Parent / Guardian</small>{profile.guardians.length?profile.guardians.map(g=><div key={g.id}><strong>{g.name}</strong><br/><small>{g.relationship} · {g.email}</small></div>):<strong>Not linked</strong>}</div></div><div className="table-scroll"><table><thead><tr><th>Date</th><th>Enrollment Event</th><th>From</th><th>To</th><th>Changed By</th></tr></thead><tbody>{history.length?history.map(h=><tr key={h.id}><td>{new Date(h.created_at).toLocaleString()}</td><td>{h.event_type.replaceAll("_"," ")}</td><td>{h.from_unit||"—"}</td><td>{h.to_unit||"—"}</td><td>{h.actor}</td></tr>):<tr><td colSpan="5" className="empty-cell">No history recorded.</td></tr>}</tbody></table></div></section>}</div>;
}
