import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
export default function AdminCommunication({ui}){
 const[data,setData]=useState(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[role,setRole]=useState("ALL");
 useEffect(()=>{api.get("/api/v1/admin/communication").then(r=>setData(r.data)).catch(e=>setError(e?.response?.data?.detail||"Unable to load communication."))},[]);
 const rows=useMemo(()=>{if(!data)return[];const q=query.trim().toLowerCase();return data.messages.filter(x=>(role==="ALL"||x.sender_role===role||x.recipient_role===role)&&(!q||[x.sender,x.recipient,x.subject,x.body,x.student_name].some(v=>String(v||"").toLowerCase().includes(q))))},[data,query,role]);
 return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Institution Admin</span><h1>Communication</h1><p>Institution-wide oversight of academic messages exchanged by faculty, students and linked guardians.</p></div></section>
 {error&&<div className="error">{error}</div>}{data&&<><div className="module-kpis"><article><small>Messages</small><strong>{data.summary.messages}</strong></article><article><small>Teacher Sent</small><strong>{data.summary.teacher_sent}</strong></article><article><small>Parent Sent</small><strong>{data.summary.parent_sent}</strong></article><article><small>To Students</small><strong>{data.summary.to_students}</strong></article><article><small>To Parents</small><strong>{data.summary.to_parents}</strong></article></div>
 <section className="panel structure-table"><div className="panel-title"><b>Communication Register</b><span>{rows.length} visible messages</span></div><div className="form-grid"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search sender, recipient, subject or message..." /><select value={role} onChange={e=>setRole(e.target.value)}><option value="ALL">All roles</option><option>Teacher</option><option>Student</option><option>Parent / Guardian</option></select></div>
 <div className="table-scroll"><table><thead><tr><th>From</th><th>To</th><th>Student Context</th><th>Subject</th><th>Message</th><th>Status</th><th>Sent</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><b>{x.sender}</b><br/><small>{x.sender_role}</small></td><td><b>{x.recipient}</b><br/><small>{x.recipient_role}</small></td><td>{x.student_name||"—"}</td><td>{x.subject}</td><td>{x.body}</td><td>{x.status}</td><td>{new Date(x.created_at).toLocaleString()}</td></tr>):<tr><td colSpan="7" className="empty-cell">No messages match these filters.</td></tr>}</tbody></table></div></section></>}</div>
}
