import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
export default function AdminCommunication({ui}){
 const[data,setData]=useState(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[role,setRole]=useState("ALL"),[form,setForm]=useState({recipient_user_id:"",student_user_id:"",subject:"",body:""}); const load=()=>api.get("/api/v1/admin/communication").then(r=>{setData(r.data);setError("")}).catch(e=>setError(e?.response?.data?.detail||"Unable to load communication.")); useEffect(()=>{load()},[]); const send=async e=>{e.preventDefault();try{await api.post("/api/v1/admin/communication",{recipient_user_id:Number(form.recipient_user_id),student_user_id:form.student_user_id?Number(form.student_user_id):null,subject:form.subject,body:form.body});setForm({recipient_user_id:"",student_user_id:"",subject:"",body:""});load()}catch(e){setError(e?.response?.data?.detail||"Unable to send message.")}};
 const editMessage=async x=>{const recipient=prompt("Recipient user ID",String(x.recipient_user_id));if(recipient===null)return;const student=prompt("Student context ID (blank for none)",x.student_user_id?String(x.student_user_id):"");if(student===null)return;const subject=prompt("Subject",x.subject);if(subject===null)return;const body=prompt("Message",x.body);if(body===null)return;try{await api.put("/api/v1/admin/communication/"+x.id,{recipient_user_id:Number(recipient),student_user_id:student?Number(student):null,subject,body});load()}catch(e){setError(e?.response?.data?.detail||"Unable to update message.")}};const rows=useMemo(()=>{if(!data)return[];const q=query.trim().toLowerCase();return data.messages.filter(x=>(role==="ALL"||x.sender_role===role||x.recipient_role===role)&&(!q||[x.sender,x.recipient,x.subject,x.body,x.student_name].some(v=>String(v||"").toLowerCase().includes(q))))},[data,query,role]);
 return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Institution Admin</span><h1>Communication</h1><p>Institution-wide oversight of academic messages exchanged by faculty, students and linked guardians.</p></div></section>
 {error&&<div className="error">{error}</div>}{data&&<><div className="module-kpis"><article><small>Messages</small><strong>{data.summary.messages}</strong></article><article><small>Teacher Sent</small><strong>{data.summary.teacher_sent}</strong></article><article><small>Parent Sent</small><strong>{data.summary.parent_sent}</strong></article><article><small>To Students</small><strong>{data.summary.to_students}</strong></article><article><small>To Parents</small><strong>{data.summary.to_parents}</strong></article></div>
 <section className="panel"><div className="panel-title"><b>Send Institution Message</b><span>Direct message to an active institution user</span></div><form className="form-grid" onSubmit={send}><select required value={form.recipient_user_id} onChange={e=>setForm({...form,recipient_user_id:e.target.value})}><option value="">Select recipient</option>{data.recipients.map(x=><option key={x.id} value={x.id}>{x.name} — {x.role}</option>)}</select><select value={form.student_user_id} onChange={e=>setForm({...form,student_user_id:e.target.value})}><option value="">No student context</option>{data.recipients.filter(x=>x.role==="Student").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input required minLength="2" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="Subject"/><textarea required value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="Message"/><button type="submit">Send Message</button></form></section>
 <section className="panel structure-table"><div className="panel-title"><b>Communication Register</b><span>{rows.length} visible messages</span></div><div className="form-grid"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search sender, recipient, subject or message..." /><select value={role} onChange={e=>setRole(e.target.value)}><option value="ALL">All roles</option><option>Teacher</option><option>Student</option><option>Parent / Guardian</option></select></div>
 <div className="table-scroll"><table><thead><tr><th>From</th><th>To</th><th>Student Context</th><th>Subject</th><th>Message</th><th>Status</th><th>Sent</th><th>Action</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><b>{x.sender}</b><br/><small>{x.sender_role}</small></td><td><b>{x.recipient}</b><br/><small>{x.recipient_role}</small></td><td>{x.student_name||"—"}</td><td>{x.subject}</td><td>{x.body}</td><td>{x.status}</td><td>{new Date(x.created_at).toLocaleString()}</td><td>{x.sender_role==="Institution Admin"?<button type="button" onClick={()=>editMessage(x)}>Update</button>:"—"}</td></tr>):<tr><td colSpan="8" className="empty-cell">No messages match these filters.</td></tr>}</tbody></table></div></section></>}</div>
}
