import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
export default function AdminLMS({ui}){
 const[data,setData]=useState(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[type,setType]=useState("ALL"),[form,setForm]=useState({unit_id:"",teacher_user_id:"",work_type:"HOMEWORK",title:"",description:"",max_marks:"0",due_at:""}); const load=()=>api.get("/api/v1/admin/lms-overview").then(r=>{setData(r.data);setError("")}).catch(e=>setError(e?.response?.data?.detail||"Unable to load learning workspace.")); useEffect(()=>{load()},[]); const create=async e=>{e.preventDefault();try{await api.post("/api/v1/admin/lms",{...form,unit_id:Number(form.unit_id),teacher_user_id:Number(form.teacher_user_id),max_marks:Number(form.max_marks),due_at:form.due_at||null});setForm({unit_id:"",teacher_user_id:"",work_type:"HOMEWORK",title:"",description:"",max_marks:"0",due_at:""});load()}catch(e){setError(e?.response?.data?.detail||"Unable to create learning item.")}}; const edit=async x=>{if(x.work_type==="EXAM")return;const title=prompt("Title",x.title);if(title===null)return;const description=prompt("Instructions",x.description||"");if(description===null)return;const status=prompt("Status: PUBLISHED / DRAFT / CLOSED",x.status);if(!status)return;const teacher=data.teachers.find(t=>t.id===x.teacher_user_id);if(!teacher){setError("Assigned teacher is not currently active.");return}try{await api.put("/api/v1/admin/lms/"+x.id,{teacher_user_id:teacher.id,title,description,max_marks:x.max_marks,due_at:x.due_at,status});load()}catch(e){setError(e?.response?.data?.detail||"Unable to update learning item.")}};
 const rows=useMemo(()=>{if(!data)return[];const q=query.trim().toLowerCase();return data.items.filter(x=>(type==="ALL"||x.work_type===type)&&(!q||[x.title,x.unit_name,x.teacher_name,x.status].some(v=>String(v||"").toLowerCase().includes(q))))},[data,query,type]);
 return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Institution Admin</span><h1>Learning / LMS</h1><p>Institution-wide oversight of homework, assignments, exams, submissions and grading activity.</p></div></section>{error&&<div className="error">{error}</div>}
 {data&&<><div className="module-kpis"><article><small>Learning Items</small><strong>{data.summary.learning_items}</strong></article><article><small>Homework</small><strong>{data.summary.homework}</strong></article><article><small>Assignments</small><strong>{data.summary.assignments}</strong></article><article><small>Exams</small><strong>{data.summary.exams}</strong></article><article><small>Submissions</small><strong>{data.summary.submissions}</strong></article><article><small>Graded</small><strong>{data.summary.graded}</strong></article></div>
 <section className="panel"><div className="panel-title"><b>Create Learning Item</b><span>Homework and assignments; exams are managed separately</span></div><form className="form-grid" onSubmit={create}><select required value={form.unit_id} onChange={e=>setForm({...form,unit_id:e.target.value})}><option value="">Course / Section</option>{data.units.map(x=><option key={x.id} value={x.id}>{x.name} — {x.code}</option>)}</select><select required value={form.teacher_user_id} onChange={e=>setForm({...form,teacher_user_id:e.target.value})}><option value="">Teacher</option>{data.teachers.map(x=><option key={x.id} value={x.id}>{x.name} — Campus {x.campus_id}</option>)}</select><select value={form.work_type} onChange={e=>setForm({...form,work_type:e.target.value})}><option value="HOMEWORK">Homework</option><option value="ASSIGNMENT">Assignment</option></select><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Title"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Instructions"/><input type="number" min="0" value={form.max_marks} onChange={e=>setForm({...form,max_marks:e.target.value})} placeholder="Maximum marks"/><input type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/><button>Create & Publish</button></form></section>
 <section className="panel structure-table"><div className="panel-title"><b>Learning Activity Register</b><span>{rows.length} visible items</span></div><div className="form-grid"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title, course or faculty..." /><select value={type} onChange={e=>setType(e.target.value)}><option value="ALL">All learning types</option><option value="HOMEWORK">Homework</option><option value="ASSIGNMENT">Assignments</option><option value="EXAM">Exams</option></select></div>
 <div className="table-scroll"><table><thead><tr><th>Type</th><th>Title</th><th>Academic Unit</th><th>Faculty</th><th>Max Marks</th><th>Submissions</th><th>Graded</th><th>Due</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td>{x.work_type}</td><td><b>{x.title}</b></td><td>{x.unit_name}</td><td>{x.teacher_name}</td><td>{x.max_marks}</td><td>{x.submissions}</td><td>{x.graded}</td><td>{x.due_at?new Date(x.due_at).toLocaleString():"—"}</td><td>{x.status}</td><td>{x.work_type==="EXAM"?"Use Exams & Results":<button type="button" onClick={()=>edit(x)}>Update</button>}</td></tr>):<tr><td colSpan="10" className="empty-cell">No learning items match these filters.</td></tr>}</tbody></table></div></section></>}</div>
}
