import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
export default function AdminTimetable({ui}){
 const[data,setData]=useState(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[scope,setScope]=useState("ALL"),[form,setForm]=useState({unit_id:"",teacher_user_id:"",title:"",starts_at:"",ends_at:"",room:""});
 const load=()=>api.get("/api/v1/admin/timetable").then(r=>setData(r.data)).catch(e=>setError(e?.response?.data?.detail||"Unable to load timetable."));
 useEffect(()=>{load()},[]); const createSession=async e=>{e.preventDefault();try{await api.post("/api/v1/admin/timetable",{...form,unit_id:Number(form.unit_id),teacher_user_id:Number(form.teacher_user_id)});setForm({unit_id:"",teacher_user_id:"",title:"",starts_at:"",ends_at:"",room:""});setError("");load()}catch(e){setError(e?.response?.data?.detail||"Unable to schedule class.")}}; const updateSession=async x=>{const status=prompt("Status: Scheduled / Completed / Cancelled",x.status);if(status===null)return;try{await api.put("/api/v1/admin/timetable/"+x.id,{teacher_user_id:x.teacher_id,title:x.title,starts_at:x.starts_at,ends_at:x.ends_at,room:x.room||"",status});load()}catch(e){setError(e?.response?.data?.detail||"Unable to update class session.")}};
 const rows=useMemo(()=>{if(!data)return[];const now=new Date();const q=query.trim().toLowerCase();return data.sessions.filter(x=>(scope==="ALL"||(scope==="UPCOMING"&&new Date(x.ends_at)>=now)||(scope==="PAST"&&new Date(x.ends_at)<now))&&(!q||[x.title,x.unit_name,x.teacher_name,x.room,x.status].some(v=>String(v||"").toLowerCase().includes(q))))},[data,query,scope]);
 return <div>
  <section className="module-context"><div><span className="eyebrow">{ui.label} • Institution Admin</span><h1>Timetable</h1><p>Institution-wide class schedule visibility across academic units, faculty and rooms.</p></div></section>
  {error&&<div className="error">{error}</div>}
  {data&&<>
   <div className="module-kpis"><article><small>Total Sessions</small><strong>{data.summary.total}</strong></article><article><small>Upcoming</small><strong>{data.summary.upcoming}</strong></article><article><small>Teachers Scheduled</small><strong>{data.summary.teachers}</strong></article><article><small>Academic Units</small><strong>{data.summary.academic_units}</strong></article><article><small>Rooms in Use</small><strong>{data.summary.rooms}</strong></article></div>
   <section className="panel"><div className="panel-title"><b>Schedule Class</b><span>Teacher, course and room conflicts are checked automatically</span></div><form className="form-grid" onSubmit={createSession}><select required value={form.unit_id} onChange={e=>setForm({...form,unit_id:e.target.value})}><option value="">Course / Section</option>{data.units.map(x=><option key={x.id} value={x.id}>{x.name} — {x.code}</option>)}</select><select required value={form.teacher_user_id} onChange={e=>setForm({...form,teacher_user_id:e.target.value})}><option value="">Teacher</option>{data.teachers.map(x=><option key={x.id} value={x.id}>{x.name} — Campus {x.campus_id}</option>)}</select><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Session title"/><input required type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/><input required type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/><input value={form.room} onChange={e=>setForm({...form,room:e.target.value})} placeholder="Room / Lab"/><button>Schedule Class</button></form></section>
   <section className="panel structure-table"><div className="panel-title"><b>Institution Timetable</b><span>{rows.length} visible sessions</span></div>
    <div className="form-grid"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search session, faculty, course or room..." /><select value={scope} onChange={e=>setScope(e.target.value)}><option value="ALL">All sessions</option><option value="UPCOMING">Upcoming</option><option value="PAST">Past</option></select></div>
    <div className="table-scroll"><table><thead><tr><th>Session</th><th>Academic Unit</th><th>Faculty</th><th>Starts</th><th>Ends</th><th>Room</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><b>{x.title}</b></td><td>{x.unit_name}<br/><small>{String(x.unit_type||"").replaceAll("_"," ")}</small></td><td>{x.teacher_name}</td><td>{new Date(x.starts_at).toLocaleString()}</td><td>{new Date(x.ends_at).toLocaleString()}</td><td>{x.room||"TBA"}</td><td>{x.status}</td><td><button type="button" onClick={()=>updateSession(x)}>Update</button></td></tr>):<tr><td colSpan="8" className="empty-cell">No timetable sessions match these filters.</td></tr>}</tbody></table></div>
   </section>
  </>}
 </div>
}
