import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
const FEE_UI={
 School:{title:"School Fees & Payments",fee:"School Fee",assign:"Assign Student Fee",examples:"Tuition / Term / Transport / Activity fee",description:"Manage school tuition, term, transport and activity fee assignments, collections, balances and receipts.",search:"Search student, term fee, transport fee or code..."},
 College:{title:"Semester Fees & Payments",fee:"College Fee",assign:"Assign Semester / Student Fee",examples:"Tuition / Semester / Exam / Lab fee",description:"Manage college tuition, semester, examination and laboratory fee assignments, collections, balances and receipts.",search:"Search student, semester fee, exam fee or code..."},
 University:{title:"University Fees & Payments",fee:"University Fee",assign:"Assign Student / Academic Fee",examples:"Tuition / Credit / Hostel / Research fee",description:"Manage university tuition, credit, hostel and research-related fee assignments, collections, balances and receipts.",search:"Search student, tuition, credit, hostel or fee code..."},
};
export default function AdminFeesPayments({ui}){
 const labels=FEE_UI[ui?.label]||FEE_UI.University;
 const[rows,setRows]=useState([]),[students,setStudents]=useState([]),[summary,setSummary]=useState(null),[payments,setPayments]=useState([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("ALL"),[form,setForm]=useState({student_user_id:"",fee_code:"",title:"",amount_due:"",due_at:""}),[editForm,setEditForm]=useState(null),[paymentForm,setPaymentForm]=useState(null),[saving,setSaving]=useState(false);
 const load=()=>Promise.all([api.get("/api/v1/fee-ledger"),api.get("/api/v1/finance/summary"),api.get("/api/v1/finance/students"),api.get("/api/v1/finance/payments")]).then(([l,s,u,p])=>{setRows(l.data);setSummary(s.data);setStudents(u.data);setPayments(p.data);setError("")}).catch(e=>setError(e?.response?.data?.detail||"Unable to load fees and payments."));
 useEffect(()=>{load()},[]);
 const openEdit=x=>{setError("");setMessage("");setEditForm({id:x.id,title:x.title,amount_due:String(x.amount_due),due_at:x.due_at?String(x.due_at).slice(0,16):""})};const saveEdit=async e=>{e.preventDefault();const amount=Number(editForm.amount_due);if(!Number.isFinite(amount)||amount<=0){setError("Assigned amount must be greater than zero.");return}try{setSaving(true);setError("");await api.patch("/api/v1/fee-ledger/"+editForm.id,{title:editForm.title.trim(),amount_due:amount,due_at:editForm.due_at||null});setEditForm(null);setMessage("Fee assignment updated successfully.");await load()}catch(e){setError(e?.response?.data?.detail||"Unable to update fee assignment.")}finally{setSaving(false)}};const createFee=async e=>{e.preventDefault();try{setSaving(true);setError("");await api.post("/api/v1/fee-ledger",{...form,student_user_id:Number(form.student_user_id),amount_due:Number(form.amount_due),due_at:form.due_at||null});setForm({student_user_id:"",fee_code:"",title:"",amount_due:"",due_at:""});setMessage("Fee assigned successfully.");await load()}catch(e){setError(e?.response?.data?.detail||"Unable to assign fee.")}finally{setSaving(false)}};const openPayment=x=>{setError("");setMessage("");setPaymentForm({id:x.id,title:x.title,balance:Number(x.balance),amount:String(x.balance),reference:""})};const savePayment=async e=>{e.preventDefault();const amount=Number(paymentForm.amount);if(!Number.isFinite(amount)||amount<=0||amount>paymentForm.balance){setError("Payment amount must be greater than zero and cannot exceed the outstanding balance.");return}try{setSaving(true);setError("");await api.post("/api/v1/fee-ledger/"+paymentForm.id+"/payments",{amount,reference:paymentForm.reference.trim()});setPaymentForm(null);setMessage("Payment recorded successfully.");await load()}catch(e){setError(e?.response?.data?.detail||"Unable to record payment.")}finally{setSaving(false)}};const cancel=async x=>{if(!confirm("Cancel this fee assignment?"))return;try{await api.post("/api/v1/fee-ledger/"+x.id+"/cancel");load()}catch(e){setError(e?.response?.data?.detail||"Unable to cancel fee.")}};const exportCsv=async()=>{try{const r=await api.get("/api/v1/finance/report");const p=r.data.payments||[];const esc=v=>'"'+String(v??"").replaceAll('"','""')+'"';const csv=["Receipt,Student,Email,Fee Code,Fee,Amount,Reference,Paid At",...p.map(x=>[x.receipt_no,x.student_name,x.student_email,x.fee_code,x.fee_title,x.amount,x.reference,x.paid_at].map(esc).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="gaint-finance-report.csv";a.click();URL.revokeObjectURL(a.href)}catch(e){setError(e?.response?.data?.detail||"Unable to export finance report.")}}; const names=useMemo(()=>Object.fromEntries(students.map(x=>[x.id,x])),[students]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return rows.filter(x=>(status==="ALL"||x.status===status)&&(!q||[x.fee_code,x.title,names[x.student_user_id]?.name,names[x.student_user_id]?.email].some(v=>String(v||"").toLowerCase().includes(q))))},[rows,names,query,status]);
 return <div>
  <section className="module-context"><div><span className="eyebrow">{ui.label} • Institution Admin</span><h1>{labels.title}</h1><p>{labels.description}</p></div></section>
  {error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}
  <div className="finance-kpis"><article><small>Assigned</small><strong>{money(summary?.assigned)}</strong></article><article><small>Collected</small><strong>{money(summary?.collected)}</strong></article><article><small>Outstanding</small><strong>{money(summary?.outstanding)}</strong></article><article><small>Paid / Partial / Due</small><strong>{summary?summary.paid_count+" / "+summary.partial_count+" / "+summary.due_count:"—"}</strong></article><article><small>Payments</small><strong>{payments.length}</strong></article></div>
  <section className="panel"><div className="panel-title"><b>{labels.assign}</b><button type="button" onClick={exportCsv}>Export Payments CSV</button></div><form className="form-grid" onSubmit={createFee}><select required value={form.student_user_id} onChange={e=>setForm({...form,student_user_id:e.target.value})}><option value="">Select student</option>{students.map(x=><option key={x.id} value={x.id}>{x.name} — {x.email}</option>)}</select><input required value={form.fee_code} onChange={e=>setForm({...form,fee_code:e.target.value})} placeholder="Fee code"/><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder={labels.examples}/><input required type="number" min="0.01" step="0.01" value={form.amount_due} onChange={e=>setForm({...form,amount_due:e.target.value})} placeholder="Amount"/><input type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/><button disabled={saving}>{saving?"Saving...":"Assign "+labels.fee}</button></form></section>
  <section className="panel structure-table"><div className="panel-title"><b>{labels.fee} Ledger</b><span>{visible.length} visible entries</span></div>
   <div className="form-grid"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={labels.search} /><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option>{["DUE","PARTIAL","PAID","CANCELLED"].map(x=><option key={x}>{x}</option>)}</select></div>
   <div className="table-scroll"><table><thead><tr><th>Student</th><th>{labels.fee}</th><th>Description</th><th>Assigned</th><th>Collected</th><th>Balance</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.length?visible.map(x=><tr key={x.id}><td><b>{names[x.student_user_id]?.name||("Student #"+x.student_user_id)}</b><br/><small>{names[x.student_user_id]?.email||""}</small></td><td>{x.fee_code}</td><td>{x.title}</td><td>{money(x.amount_due)}</td><td>{money(x.amount_paid)}</td><td>{money(x.balance)}</td><td><b>{x.status}</b></td><td>{x.status!=="CANCELLED"&&<button type="button" onClick={()=>openEdit(x)}>Update</button>} {x.status!=="CANCELLED"&&x.balance>0&&<button type="button" onClick={()=>openPayment(x)}>Record Payment</button>} {x.status!=="CANCELLED"&&x.amount_paid<=0&&<button type="button" onClick={()=>cancel(x)}>Cancel</button>}</td></tr>):<tr><td colSpan="8" className="empty-cell">No fee records match these filters.</td></tr>}</tbody></table></div>
  </section>
  {editForm&&<section className="panel"><div className="panel-title"><b>Update Fee Assignment</b><button type="button" className="table-action" onClick={()=>setEditForm(null)}>Cancel</button></div><form className="form-grid" onSubmit={saveEdit}><input required value={editForm.title} onChange={e=>setEditForm(x=>({...x,title:e.target.value}))} placeholder="Fee description"/><input required type="number" min="0.01" step="0.01" value={editForm.amount_due} onChange={e=>setEditForm(x=>({...x,amount_due:e.target.value}))} placeholder="Assigned amount"/><input type="datetime-local" value={editForm.due_at} onChange={e=>setEditForm(x=>({...x,due_at:e.target.value}))}/><button disabled={saving}>{saving?"Saving...":"Save Changes"}</button></form></section>}
  {paymentForm&&<section className="panel"><div className="panel-title"><b>Record Payment — {paymentForm.title}</b><button type="button" className="table-action" onClick={()=>setPaymentForm(null)}>Cancel</button></div><form className="form-grid" onSubmit={savePayment}><input required type="number" min="0.01" max={paymentForm.balance} step="0.01" value={paymentForm.amount} onChange={e=>setPaymentForm(x=>({...x,amount:e.target.value}))} placeholder="Payment amount"/><input value={paymentForm.reference} onChange={e=>setPaymentForm(x=>({...x,reference:e.target.value}))} placeholder="Payment reference"/><button disabled={saving}>{saving?"Recording...":"Record Payment"}</button></form><small>Outstanding balance: {money(paymentForm.balance)}</small></section>}
  <section className="panel structure-table"><div className="panel-title"><b>Recent Payments</b><span>{payments.length} recorded payments</span></div><div className="table-scroll"><table><thead><tr><th>Receipt</th><th>Student</th><th>Fee</th><th>Amount</th><th>Reference</th><th>Paid At</th></tr></thead><tbody>{payments.slice(0,100).map(x=><tr key={x.id}><td><b>{x.receipt_no}</b></td><td>{x.student_name}</td><td>{x.fee_title}<br/><small>{x.fee_code}</small></td><td>{money(x.amount)}</td><td>{x.reference||"—"}</td><td>{new Date(x.paid_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>
 </div>
}
