import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
const EXAM_UI={
 School:{title:"Exams & Report Cards",assessment:"Exam",create:"Create School Exam",unit:"Class / Subject",person:"Teacher",marks:"Marks",result:"Report Card Result",description:"Manage unit tests, term examinations, annual examinations, marks, grades and report-card publication.",placeholder:"Unit / Term / Annual exam title",search:"Search exam, class, subject or teacher..."},
 College:{title:"Exams & Results",assessment:"Assessment",create:"Create College Assessment",unit:"Semester / Course",person:"Faculty",marks:"Marks",result:"Semester Result",description:"Manage internal assessments, practicals, semester examinations, marks, grades and result publication.",placeholder:"Internal / Practical / Semester exam title",search:"Search assessment, semester, course or faculty..."},
 University:{title:"Assessments & Results",assessment:"Assessment",create:"Create University Assessment",unit:"Course / Cohort",person:"Faculty",marks:"Marks / Score",result:"Academic Result",description:"Manage continuous assessment, mid-semester and semester-end examinations, grades and academic result publication.",placeholder:"Continuous / Mid / Semester-End assessment title",search:"Search assessment, course, cohort or faculty..."},
};
export default function AdminExamsResults({ui}){
 const labels=EXAM_UI[ui?.label]||EXAM_UI.University;
 const[data,setData]=useState(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("ALL"),[form,setForm]=useState({unit_id:"",teacher_user_id:"",title:"",max_marks:"100",due_at:""}),[register,setRegister]=useState(null),[marksForm,setMarksForm]=useState(null),[message,setMessage]=useState(""),[saving,setSaving]=useState(false); const load=()=>api.get("/api/v1/admin/exams-results").then(r=>{setData(r.data);setError("")}).catch(e=>setError(e?.response?.data?.detail||"Unable to load exams and results.")); useEffect(()=>{load()},[]); const createExam=async e=>{e.preventDefault();try{await api.post("/api/v1/admin/exams?teacher_user_id="+form.teacher_user_id,{unit_id:Number(form.unit_id),work_type:"EXAM",title:form.title,description:"",max_marks:Number(form.max_marks),due_at:form.due_at||null});setForm({unit_id:"",teacher_user_id:"",title:"",max_marks:"100",due_at:""});load()}catch(e){setError(e?.response?.data?.detail||"Unable to create exam.")}}; const openResults=async id=>{try{const r=await api.get("/api/v1/admin/exams/"+id+"/results");setRegister(r.data)}catch(e){setError(e?.response?.data?.detail||"Unable to load result register.")}}; const editMarks=(exam,student,name,current,currentRemarks,maxMarks)=>{setError("");setMessage("");setMarksForm({exam,student,name,marks:current??"",remarks:currentRemarks||"",maxMarks:Number(maxMarks)})}; const saveMarks=async e=>{e.preventDefault();const marks=Number(marksForm.marks);if(!Number.isFinite(marks)||marks<0||marks>marksForm.maxMarks){setError("Marks must be between 0 and "+marksForm.maxMarks+".");return}try{setSaving(true);setError("");await api.put("/api/v1/admin/exams/"+marksForm.exam+"/results",{student_user_id:marksForm.student,marks,remarks:marksForm.remarks.trim()});const exam=marksForm.exam;setMarksForm(null);setMessage("Marks saved successfully.");await openResults(exam);await load()}catch(e){setError(e?.response?.data?.detail||"Unable to save result.")}finally{setSaving(false)}}; const approve=async id=>{if(!confirm("Approve and publish all results for this exam? Published results will be locked."))return;try{await api.post("/api/v1/admin/exams/"+id+"/approve");openResults(id);load()}catch(e){setError(e?.response?.data?.detail||"Unable to approve results.")}};
 const rows=useMemo(()=>{if(!data)return[];const q=query.trim().toLowerCase();return data.exams.filter(x=>(status==="ALL"||x.status===status)&&(!q||[x.title,x.unit_name,x.teacher_name,x.status].some(v=>String(v||"").toLowerCase().includes(q))))},[data,query,status]);
 return <div>
  <section className="module-context"><div><span className="eyebrow">{ui.label} • Institution Admin</span><h1>{labels.title}</h1><p>{labels.description}</p></div></section>
  {error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}
  {data&&<>
   <div className="module-kpis"><article><small>{labels.assessment}s</small><strong>{data.summary.exams}</strong></article><article><small>Result Records</small><strong>{data.summary.results}</strong></article><article><small>Published</small><strong>{data.summary.published}</strong></article><article><small>Draft</small><strong>{data.summary.draft}</strong></article><article><small>Pass Rate</small><strong>{data.summary.pass_rate==null?"—":data.summary.pass_rate+"%"}</strong></article></div>
   <section className="panel"><div className="panel-title"><b>{labels.create}</b><span>Assign {labels.person.toLowerCase()} and assessment details</span></div><form className="form-grid" onSubmit={createExam}><select required value={form.unit_id} onChange={e=>setForm({...form,unit_id:e.target.value})}><option value="">{labels.unit}</option>{data.units.map(x=><option key={x.id} value={x.id}>{x.name} — {x.code}</option>)}</select><select required value={form.teacher_user_id} onChange={e=>setForm({...form,teacher_user_id:e.target.value})}><option value="">{labels.person}</option>{data.teachers.map(x=><option key={x.id} value={x.id}>{x.name} — Campus {x.campus_id}</option>)}</select><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder={labels.placeholder}/><input required type="number" min="1" value={form.max_marks} onChange={e=>setForm({...form,max_marks:e.target.value})} placeholder="Maximum marks"/><input type="datetime-local" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/><button>{labels.create}</button></form></section>
   {register&&<section className="panel structure-table"><div className="panel-title"><b>{register.exam.title} — {labels.result} Register</b><button type="button" onClick={()=>approve(register.exam.id)}>Approve & Publish</button></div><div className="table-scroll"><table><thead><tr><th>Student</th><th>{labels.marks}</th><th>Percentage</th><th>Grade</th><th>Result</th><th>Remarks</th><th>Published</th><th>Action</th></tr></thead><tbody>{register.students.map(x=><tr key={x.student_id}><td><b>{x.student_name}</b></td><td>{x.marks??"—"} / {register.exam.max_marks}</td><td>{x.percentage==null?"—":x.percentage+"%"}</td><td>{x.grade||"—"}</td><td>{x.result_status||"—"}</td><td>{x.remarks||"—"}</td><td>{x.published?"Yes":"No"}</td><td><button type="button" disabled={x.published} onClick={()=>editMarks(register.exam.id,x.student_id,x.student_name,x.marks,x.remarks,register.exam.max_marks)}>Enter / Update Marks</button></td></tr>)}</tbody></table></div></section>}
   {marksForm&&<section className="panel"><div className="panel-title"><b>Enter / Update Marks — {marksForm.name}</b><button type="button" className="table-action" onClick={()=>setMarksForm(null)}>Cancel</button></div><form className="form-grid" onSubmit={saveMarks}><label>Marks<input required type="number" min="0" max={marksForm.maxMarks} step="0.01" value={marksForm.marks} onChange={e=>setMarksForm(x=>({...x,marks:e.target.value}))}/></label><label>Remarks<input value={marksForm.remarks} onChange={e=>setMarksForm(x=>({...x,remarks:e.target.value}))} placeholder="Optional result remarks"/></label><button disabled={saving}>{saving?"Saving...":"Save Marks"}</button></form><small>Maximum marks: {marksForm.maxMarks}</small></section>}
   <section className="panel structure-table"><div className="panel-title"><b>{labels.assessment} Register</b><span>{rows.length} visible exams</span></div>
    <div className="form-grid"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={labels.search} /><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option><option value="AWAITING RESULTS">Awaiting Results</option><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></select></div>
    <div className="table-scroll"><table><thead><tr><th>{labels.assessment}</th><th>{labels.unit}</th><th>{labels.person}</th><th>Max {labels.marks}</th><th>Results</th><th>Pass / Fail</th><th>Average</th><th>Publication</th><th>Action</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><b>{x.title}</b>{x.due_at&&<><br/><small>{new Date(x.due_at).toLocaleString()}</small></>}</td><td>{x.unit_name}</td><td>{x.teacher_name}</td><td>{x.max_marks}</td><td>{x.results}</td><td>{x.passed} / {x.failed}</td><td>{x.average_percentage==null?"—":x.average_percentage+"%"}</td><td><b>{x.status}</b>{x.results>0&&<><br/><small>{x.published}/{x.results} published</small></>}</td><td><button type="button" onClick={()=>openResults(x.id)}>Manage Results</button></td></tr>):<tr><td colSpan="9" className="empty-cell">No exams match these filters.</td></tr>}</tbody></table></div>
   </section>
  </>}
 </div>
}
