import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
const pretty=s=>String(s||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function AdminAcademics({ui}){
 const[data,setData]=useState(null),[error,setError]=useState(""),[type,setType]=useState("ALL"),[query,setQuery]=useState(""),[form,setForm]=useState({unit_type:"CAMPUS",name:"",code:"",parent_id:"",campus_id:"1",status:"Active"});
 const load=()=>api.get("/api/v1/admin/academics-overview").then(r=>setData(r.data)).catch(e=>setError(e?.response?.data?.detail||"Unable to load academics."));
 useEffect(()=>{load()},[]); const addUnit=async e=>{e.preventDefault();try{await api.post("/api/v1/academic-structure",{...form,campus_id:Number(form.campus_id),parent_id:form.parent_id?Number(form.parent_id):null});setForm({unit_type:"CAMPUS",name:"",code:"",parent_id:"",campus_id:"1",status:"Active"});setError("");load()}catch(e){setError(e?.response?.data?.detail||"Unable to add academic unit.")}}; const removeUnit=async x=>{if(!confirm("Delete "+x.name+"?"))return;try{await api.delete("/api/v1/academic-structure/"+x.id);load()}catch(e){setError(e?.response?.data?.detail||"Unable to delete academic unit.")}};
 const types=useMemo(()=>data?Object.keys(data.type_counts).sort():[],[data]);
 const rows=useMemo(()=>{if(!data)return[];const q=query.trim().toLowerCase();return data.units.filter(x=>(type==="ALL"||x.unit_type===type)&&(!q||[x.name,x.code,x.parent,x.unit_type].some(v=>String(v).toLowerCase().includes(q))))},[data,type,query]);
 return <div>
  <section className="module-context"><div><span className="eyebrow">{ui.label} • Institution Admin</span><h1>Academics</h1><p>Institution-wide academic hierarchy, programs, courses, sections and assignment coverage.</p></div></section>
  {error&&<div className="error">{error}</div>}
  {data&&<>
   <div className="module-kpis"><article><small>Academic Units</small><strong>{data.summary.units}</strong></article><article><small>Programs</small><strong>{data.summary.programs}</strong></article><article><small>Courses</small><strong>{data.summary.courses}</strong></article><article><small>Sections / Batches</small><strong>{data.summary.sections}</strong></article><article><small>Assigned Students</small><strong>{data.summary.assigned_students}</strong></article><article><small>Assigned Teachers</small><strong>{data.summary.assigned_teachers}</strong></article></div>
   {(data.summary.unassigned_students>0||data.summary.unassigned_teachers>0)&&<section className="panel"><div className="panel-title"><b>Assignment Attention</b><span>Action required</span></div><p>{data.summary.unassigned_students} student(s) and {data.summary.unassigned_teachers} teacher(s) currently have no active academic assignment. Use <b>Enrollment & Assignments</b> to connect them.</p></section>}
   <section className="panel"><div className="panel-title"><b>Add Academic Unit</b><span>Build the hierarchy from Campus downward</span></div><form className="form-grid" onSubmit={addUnit}><select value={form.unit_type} onChange={e=>setForm({...form,unit_type:e.target.value,parent_id:""})}>{["CAMPUS","SCHOOL_FACULTY","DEPARTMENT","PROGRAM","ACADEMIC_PERIOD","COURSE","SECTION_BATCH"].map(x=><option key={x} value={x}>{pretty(x)}</option>)}</select><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Unit name"/><input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="Unique code"/><input required type="number" min="1" value={form.campus_id} onChange={e=>setForm({...form,campus_id:e.target.value})} placeholder="Campus ID"/>{form.unit_type!=="CAMPUS"&&<select required value={form.parent_id} onChange={e=>setForm({...form,parent_id:e.target.value})}><option value="">Select parent</option>{data.units.map(x=><option key={x.id} value={x.id}>{pretty(x.unit_type)} — {x.name}</option>)}</select>}<button>Add Academic Unit</button></form></section>
   <section className="panel structure-table"><div className="panel-title"><b>Academic Catalogue</b><span>{rows.length} visible units</span></div>
    <div className="form-grid"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, code or parent..." /><select value={type} onChange={e=>setType(e.target.value)}><option value="ALL">All unit types</option>{types.map(x=><option key={x} value={x}>{pretty(x)}</option>)}</select></div>
    <div className="table-scroll"><table><thead><tr><th>Type</th><th>Name</th><th>Code</th><th>Parent</th><th>Students</th><th>Teachers</th><th>Links</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td>{pretty(x.unit_type)}</td><td><b>{x.name}</b></td><td>{x.code}</td><td>{x.parent}</td><td>{x.students}</td><td>{x.teachers}</td><td>{x.assignments}</td><td>{x.status}</td><td><button type="button" onClick={()=>removeUnit(x)}>Delete</button></td></tr>):<tr><td colSpan="9" className="empty-cell">No academic units match these filters.</td></tr>}</tbody></table></div>
   </section>
  </>}
 </div>
}
