import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
export default function AdminLMS({ui}){
 const[data,setData]=useState(null),[error,setError]=useState(""),[query,setQuery]=useState(""),[type,setType]=useState("ALL");
 useEffect(()=>{api.get("/api/v1/admin/lms-overview").then(r=>setData(r.data)).catch(e=>setError(e?.response?.data?.detail||"Unable to load learning workspace."))},[]);
 const rows=useMemo(()=>{if(!data)return[];const q=query.trim().toLowerCase();return data.items.filter(x=>(type==="ALL"||x.work_type===type)&&(!q||[x.title,x.unit_name,x.teacher_name,x.status].some(v=>String(v||"").toLowerCase().includes(q))))},[data,query,type]);
 return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Institution Admin</span><h1>Learning / LMS</h1><p>Institution-wide oversight of homework, assignments, exams, submissions and grading activity.</p></div></section>{error&&<div className="error">{error}</div>}
 {data&&<><div className="module-kpis"><article><small>Learning Items</small><strong>{data.summary.learning_items}</strong></article><article><small>Homework</small><strong>{data.summary.homework}</strong></article><article><small>Assignments</small><strong>{data.summary.assignments}</strong></article><article><small>Exams</small><strong>{data.summary.exams}</strong></article><article><small>Submissions</small><strong>{data.summary.submissions}</strong></article><article><small>Graded</small><strong>{data.summary.graded}</strong></article></div>
 <section className="panel structure-table"><div className="panel-title"><b>Learning Activity Register</b><span>{rows.length} visible items</span></div><div className="form-grid"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title, course or faculty..." /><select value={type} onChange={e=>setType(e.target.value)}><option value="ALL">All learning types</option><option value="HOMEWORK">Homework</option><option value="ASSIGNMENT">Assignments</option><option value="EXAM">Exams</option></select></div>
 <div className="table-scroll"><table><thead><tr><th>Type</th><th>Title</th><th>Academic Unit</th><th>Faculty</th><th>Max Marks</th><th>Submissions</th><th>Graded</th><th>Due</th><th>Status</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td>{x.work_type}</td><td><b>{x.title}</b></td><td>{x.unit_name}</td><td>{x.teacher_name}</td><td>{x.max_marks}</td><td>{x.submissions}</td><td>{x.graded}</td><td>{x.due_at?new Date(x.due_at).toLocaleString():"—"}</td><td>{x.status}</td></tr>):<tr><td colSpan="9" className="empty-cell">No learning items match these filters.</td></tr>}</tbody></table></div></section></>}</div>
}
