import React,{useEffect,useState} from "react";import {api} from "../api";
export default function CampusTransport({ui}){
 const terms=ui.label==="School"?{title:"School Transport",route:"Bus Route",vehicle:"School Bus",stop:"Pickup / Drop Stop",allocation:"Student Bus Allocation"}:{title:ui.label+" Transport",route:"Route",vehicle:"Vehicle",stop:"Boarding Stop",allocation:"Student Transport Allocation"};
 const[d,setD]=useState(null),[err,setErr]=useState(""),[route,setRoute]=useState({name:"",code:""}),[vehicle,setVehicle]=useState({vehicle_number:"",label:""}),[stop,setStop]=useState({route_id:"",name:"",stop_order:"0"}),[allocation,setAllocation]=useState({student_user_id:"",route_id:"",vehicle_id:"",stop_id:"",pickup_time:"",drop_time:""});
 const load=()=>api.get("/api/v1/campus/transport").then(r=>{setD(r.data);setErr("")}).catch(e=>setErr(e?.response?.data?.detail||"Unable to load campus transport."));
 useEffect(()=>{load()},[]);
 const post=async(path,payload,reset)=>{try{setErr("");await api.post(path,payload);reset();await load()}catch(e){setErr(e?.response?.data?.detail||"Unable to save transport record.")}};
 const campus=()=>d?.campus_id;
 const s=d?.summary||{};
 return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Campus Admin</span><h1>{terms.title}</h1><p>Manage routes, stops, vehicles and student transport allocations for your campus.</p></div></section>{err&&<div className="error">{err}</div>}{d&&<><div className="module-kpis"><article><small>Routes</small><strong>{s.routes}</strong></article><article><small>Active Routes</small><strong>{s.active_routes}</strong></article><article><small>Vehicles</small><strong>{s.vehicles}</strong></article><article><small>Active Vehicles</small><strong>{s.active_vehicles}</strong></article><article><small>Students Using Transport</small><strong>{s.allocations}</strong></article></div>
 <div className="setup-grid"><section className="panel"><div className="panel-title"><b>Add {terms.route}</b></div><form className="form-grid" onSubmit={e=>{e.preventDefault();post("/api/v1/campus/transport/routes",{...route,campus_id:campus()},()=>setRoute({name:"",code:""}))}}><input required value={route.name} onChange={e=>setRoute({...route,name:e.target.value})} placeholder="Route name"/><input required value={route.code} onChange={e=>setRoute({...route,code:e.target.value})} placeholder="Route code"/><button>Add Route</button></form></section>
 <section className="panel"><div className="panel-title"><b>Add {terms.vehicle}</b></div><form className="form-grid" onSubmit={e=>{e.preventDefault();post("/api/v1/campus/transport/vehicles",{...vehicle,campus_id:campus()},()=>setVehicle({vehicle_number:"",label:""}))}}><input required value={vehicle.vehicle_number} onChange={e=>setVehicle({...vehicle,vehicle_number:e.target.value})} placeholder="Vehicle number"/><input value={vehicle.label} onChange={e=>setVehicle({...vehicle,label:e.target.value})} placeholder="Vehicle label"/><button>Add Vehicle</button></form></section></div>
 <div className="setup-grid"><section className="panel"><div className="panel-title"><b>Add {terms.stop}</b></div><form className="form-grid" onSubmit={e=>{e.preventDefault();post("/api/v1/campus/transport/stops",{route_id:Number(stop.route_id),name:stop.name,stop_order:Number(stop.stop_order)},()=>setStop({route_id:"",name:"",stop_order:"0"}))}}><select required value={stop.route_id} onChange={e=>setStop({...stop,route_id:e.target.value})}><option value="">Select route</option>{(d.routes||[]).filter(x=>x.status==="Active").map(x=><option key={x.id} value={x.id}>{x.name} — {x.code}</option>)}</select><input required value={stop.name} onChange={e=>setStop({...stop,name:e.target.value})} placeholder="Stop name"/><input type="number" min="0" value={stop.stop_order} onChange={e=>setStop({...stop,stop_order:e.target.value})}/><button>Add Stop</button></form></section>
 <section className="panel"><div className="panel-title"><b>{terms.allocation}</b></div><form className="form-grid" onSubmit={e=>{e.preventDefault();post("/api/v1/campus/transport/allocations",{student_user_id:Number(allocation.student_user_id),route_id:Number(allocation.route_id),vehicle_id:allocation.vehicle_id?Number(allocation.vehicle_id):null,stop_id:Number(allocation.stop_id),pickup_time:allocation.pickup_time,drop_time:allocation.drop_time,status:"Active"},()=>setAllocation({student_user_id:"",route_id:"",vehicle_id:"",stop_id:"",pickup_time:"",drop_time:""}))}}><select required value={allocation.student_user_id} onChange={e=>setAllocation({...allocation,student_user_id:e.target.value})}><option value="">Select student</option>{(d.students||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select required value={allocation.route_id} onChange={e=>setAllocation({...allocation,route_id:e.target.value,stop_id:"",vehicle_id:""})}><option value="">Select route</option>{(d.routes||[]).filter(x=>x.status==="Active").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select required value={allocation.stop_id} onChange={e=>setAllocation({...allocation,stop_id:e.target.value})}><option value="">Select stop</option>{(d.stops||[]).filter(x=>String(x.route_id)===String(allocation.route_id)).map(x=><option key={x.id} value={x.id}>{x.stop_order}. {x.name}</option>)}</select><select value={allocation.vehicle_id} onChange={e=>setAllocation({...allocation,vehicle_id:e.target.value})}><option value="">No vehicle</option>{(d.vehicles||[]).filter(x=>x.status==="Active").map(x=><option key={x.id} value={x.id}>{x.vehicle_number}</option>)}</select><input type="time" required value={allocation.pickup_time} onChange={e=>setAllocation({...allocation,pickup_time:e.target.value})}/><input type="time" required value={allocation.drop_time} onChange={e=>setAllocation({...allocation,drop_time:e.target.value})}/><button>Save Allocation</button></form></section></div>
 <section className="panel structure-table"><div className="panel-title"><b>Student Transport Allocations</b><span>{(d.allocations||[]).length} records</span></div><div className="table-scroll"><table><thead><tr><th>Student</th><th>{terms.route}</th><th>{terms.stop}</th><th>{terms.vehicle}</th><th>Pickup</th><th>Drop</th><th>Status</th></tr></thead><tbody>{(d.allocations||[]).length?(d.allocations||[]).map(x=><tr key={x.id}><td><b>{x.student_name}</b></td><td>{x.route_name||"—"}</td><td>{x.stop_name||"—"}</td><td>{x.vehicle_number||"—"}</td><td>{x.pickup_time||"—"}</td><td>{x.drop_time||"—"}</td><td>{x.status}</td></tr>):<tr><td colSpan="7" className="empty-cell">No transport allocations for this campus.</td></tr>}</tbody></table></div></section></>}</div>
}