import React,{useEffect,useState} from "react"; import {api} from "../api";
export default function GradeRules({ui}){
 const [rows,setRows]=useState([]),[form,setForm]=useState({name:"",min_percentage:"",max_percentage:"",grade:"",grade_point:"",result_status:"PASS"}),[err,setErr]=useState("");
 const load=()=>api.get("/api/v1/grade-rules").then(r=>setRows(r.data)).catch(e=>setErr(e?.response?.data?.detail||"Unable to load grade rules."));
 useEffect(()=>{load()},[]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 async function add(){try{await api.post("/api/v1/grade-rules",{...form,min_percentage:Number(form.min_percentage),max_percentage:Number(form.max_percentage),grade_point:form.grade_point===""?null:Number(form.grade_point)});setForm({name:"",min_percentage:"",max_percentage:"",grade:"",grade_point:"",result_status:"PASS"});setErr("");load()}catch(e){setErr(e?.response?.data?.detail||"Unable to save grade rule.")}}
 async function del(id){await api.delete("/api/v1/grade-rules/"+id);load()}
 return <div><section className="role-hero"><div><span className="eyebrow">{ui.label} Academic Policy</span><h1>Grading Scheme</h1><p>Configure institution-specific percentage, grade, grade point and result rules.</p></div></section><div className="setup-grid"><section className="panel"><div className="setup-form"><label>Rule Name<input value={form.name} onChange={e=>set("name",e.target.value)}/></label><label>Minimum %<input type="number" value={form.min_percentage} onChange={e=>set("min_percentage",e.target.value)}/></label><label>Maximum %<input type="number" value={form.max_percentage} onChange={e=>set("max_percentage",e.target.value)}/></label><label>Grade<input value={form.grade} onChange={e=>set("grade",e.target.value)}/></label><label>Grade Point<input type="number" value={form.grade_point} onChange={e=>set("grade_point",e.target.value)}/></label><label>Result<select value={form.result_status} onChange={e=>set("result_status",e.target.value)}><option>PASS</option><option>FAIL</option></select></label></div>{err&&<div className="error">{err}</div>}<button className="primary" onClick={add}>Add Grade Rule</button></section><section className="panel structure-table"><div className="table-scroll"><table><thead><tr><th>Range</th><th>Grade</th><th>Point</th><th>Result</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.min_percentage}% – {r.max_percentage}%</td><td><b>{r.grade}</b></td><td>{r.grade_point??"—"}</td><td>{r.result_status}</td><td><button className="table-action danger" onClick={()=>del(r.id)}>Delete</button></td></tr>)}</tbody></table></div></section></div></div>
}