import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
export default function ParentStudentLinks(){
 const [users,setUsers]=useState([]),[links,setLinks]=useState([]),[form,setForm]=useState({parent_user_id:"",student_user_id:"",relationship:"Guardian"}),[error,setError]=useState(""),[message,setMessage]=useState("");
 const parents=useMemo(()=>users.filter(x=>x.role==="Parent / Guardian"&&x.is_active),[users]),students=useMemo(()=>users.filter(x=>x.role==="Student"&&x.is_active),[users]);
 const load=()=>Promise.all([api.get("/api/v1/users"),api.get("/api/v1/admin/parent-student-links")]).then(([u,l])=>{setUsers(u.data);setLinks(l.data);setError("")}).catch(e=>setError(e?.response?.data?.detail||"Unable to load parent/student links."));
 useEffect(()=>{load()},[]);
 async function add(e){e.preventDefault();try{await api.post("/api/v1/admin/parent-student-links",{parent_user_id:Number(form.parent_user_id),student_user_id:Number(form.student_user_id),relationship:form.relationship});setMessage("Parent and student linked.");setError("");setForm({parent_user_id:"",student_user_id:"",relationship:"Guardian"});load()}catch(e){setError(e?.response?.data?.detail||"Unable to create link.")}}
 async function remove(id){if(!window.confirm("Remove this parent/student link?"))return;try{await api.delete("/api/v1/admin/parent-student-links/"+id);setMessage("Link removed.");setError("");load()}catch(e){setError(e?.response?.data?.detail||"Unable to remove link.")}}
 return <div className="workspace-page"><div className="page-heading"><div><span className="eyebrow">Administration</span><h1>Parent ↔ Student Links</h1><p>Connect guardians to students in the same institution.</p></div></div>{error&&<div className="error-banner">{error}</div>}{message&&<div className="success-banner">{message}</div>}
 <section className="panel"><div className="panel-title"><b>Add Link</b><span>Required for parent academic, fee and location access</span></div><form className="setup-form" onSubmit={add}><label>Parent / Guardian<select required value={form.parent_user_id} onChange={e=>setForm(x=>({...x,parent_user_id:e.target.value}))}><option value="">Select parent</option>{parents.map(x=><option value={x.id} key={x.id}>{x.name} — {x.email}</option>)}</select></label><label>Student<select required value={form.student_user_id} onChange={e=>setForm(x=>({...x,student_user_id:e.target.value}))}><option value="">Select student</option>{students.map(x=><option value={x.id} key={x.id}>{x.name} — {x.email}</option>)}</select></label><label>Relationship<input required value={form.relationship} onChange={e=>setForm(x=>({...x,relationship:e.target.value}))}/></label><button className="primary">Add Link</button></form></section>
 <section className="panel structure-table"><div className="panel-title"><b>Existing Links</b><span>{links.length} relationships</span></div><div className="table-scroll"><table><thead><tr><th>Parent / Guardian</th><th>Student</th><th>Relationship</th><th>Action</th></tr></thead><tbody>{links.length?links.map(x=><tr key={x.id}><td>{x.parent_name}<br/><small>{x.parent_email}</small></td><td>{x.student_name}<br/><small>{x.student_email}</small></td><td>{x.relationship}</td><td><button className="table-action" onClick={()=>remove(x.id)}>Remove</button></td></tr>):<tr><td colSpan="4" className="empty-cell">No parent/student links found.</td></tr>}</tbody></table></div></section></div>;
}
