import React,{useEffect,useState} from "react"; import {api} from "../api";
export default function ParentChildrenFinance({title,ui}){
 const [children,setChildren]=useState([]),[childId,setChildId]=useState(""),[fees,setFees]=useState(null),[err,setErr]=useState("");
 useEffect(()=>{api.get("/api/v1/parents/children").then(r=>{setChildren(r.data);if(r.data.length)setChildId(String(r.data[0].id))}).catch(e=>setErr(e?.response?.data?.detail||"Unable to load linked children."))},[]);
 useEffect(()=>{if(title!=="Fees"||!childId)return;api.get("/api/v1/parents/children/"+childId+"/fees").then(r=>{setFees(r.data);setErr("")}).catch(e=>setErr(e?.response?.data?.detail||"Unable to load child fee records."))},[title,childId]);
 if(title==="My Children")return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Parent / Guardian</span><h1>My Children</h1><p>Students officially linked to your parent account.</p></div><div className="hero-badge">{children.length} Linked</div></section>{err&&<div className="error">{err}</div>}<section className="panel structure-table"><div className="table-scroll"><table><thead><tr><th>Student</th><th>Email</th><th>Relationship</th></tr></thead><tbody>{children.length?children.map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.email}</td><td>{c.relationship}</td></tr>):<tr><td colSpan="3" className="empty-cell">No students are linked to this parent account.</td></tr>}</tbody></table></div></section></div>;
 const rows=fees?.records||[];
 return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Parent / Guardian</span><h1>Fees</h1><p>Finance records explicitly linked to your selected child.</p></div><label>Child<select value={childId} onChange={e=>setChildId(e.target.value)}>{children.map(c=><option key={c.id} value={c.id}>{c.name} — {c.relationship}</option>)}</select></label></section>{err&&<div className="error">{err}</div>}{fees?.message&&<div className="panel"><p>{fees.message}</p></div>}<section className="panel structure-table"><div className="table-scroll"><table><thead><tr><th>Record</th><th>Type</th><th>Category</th><th>Status</th><th>Details</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td><b>{r.name}</b></td><td>{r.module}</td><td>{r.category}</td><td>{r.status}</td><td>{r.notes||"—"}</td></tr>):<tr><td colSpan="5" className="empty-cell">No student-linked fee records available.</td></tr>}</tbody></table></div></section></div>
}
