import React,{useEffect,useState} from "react";
import {api} from "../api";

export default function ParentAcademics({title,ui}){\n const terms=ui.label==="School"?{learner:"Pupil",learners:"pupils",academics:"school academic",session:"Class Session",work:"Homework / Classwork"}:ui.label==="College"?{learner:"Student",learners:"students",academics:"college academic",session:"Class Session",work:"Assignment / Coursework"}:{learner:"Student",learners:"students",academics:"university academic",session:"Course Session",work:"Assignment / Coursework"};
 const [children,setChildren]=useState([]),[childId,setChildId]=useState(""),[data,setData]=useState(null),[err,setErr]=useState("");
 useEffect(()=>{api.get("/api/v1/parents/children").then(r=>{setChildren(r.data);if(r.data.length)setChildId(String(r.data[0].id))}).catch(e=>setErr(e?.response?.data?.detail||"Unable to load linked "+terms.learners+"."))},[]);
 useEffect(()=>{if(!childId)return;api.get("/api/v1/parents/children/"+childId+"/academics").then(r=>{setData(r.data);setErr("")}).catch(e=>setErr(e?.response?.data?.detail||"Unable to load "+terms.learner.toLowerCase()+" academics."))},[childId]);
 const attendance=data?.attendance;
 const rows=title==="Attendance"?(attendance?.sessions||[]):title==="Results"?(data?.results||[]):(data?.homework||[]);
 return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Parent / Guardian</span><h1>{title}</h1><p>Live {terms.academics} information for {terms.learners} linked to your parent / guardian account.</p></div><label>{terms.learner}<select value={childId} onChange={e=>setChildId(e.target.value)}>{children.map(c=><option key={c.id} value={c.id}>{c.name} — {c.relationship}</option>)}</select></label></section>
 {err&&<div className="error">{err}</div>}
 {title==="Attendance"&&<div className="module-kpis"><article><small>Attendance</small><strong>{attendance?.percentage==null?"—":attendance.percentage+"%"}</strong></article><article><small>Attended</small><strong>{attendance?.attended||0}</strong></article><article><small>Excused</small><strong>{attendance?.excused||0}</strong></article></div>}
 <section className="panel structure-table"><div className="panel-title"><b>{title}</b><span>{rows.length} records</span></div><div className="table-scroll"><table><thead><tr>{title==="Attendance"?<><th>{terms.session}</th><th>Date</th><th>Room</th><th>Status</th></>:title==="Results"?<><th>Exam</th><th>Marks</th><th>Percentage</th><th>Grade</th><th>Result</th></>:<><th>{terms.work}</th><th>Type</th><th>Due</th><th>Status</th><th>Score</th></>}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={r.id||r.exam_id||r.session_id||i}>{title==="Attendance"?<><td><b>{r.title}</b></td><td>{new Date(r.starts_at).toLocaleString()}</td><td>{r.room||"—"}</td><td>{r.status}</td></>:title==="Results"?<><td><b>{r.title}</b></td><td>{r.marks}</td><td>{r.percentage}%</td><td>{r.grade}</td><td>{r.result_status}</td></>:<><td><b>{r.title}</b></td><td>{r.work_type}</td><td>{r.due_at?new Date(r.due_at).toLocaleString():"—"}</td><td>{r.status}</td><td>{r.score??"—"}</td></>}</tr>):<tr><td colSpan="5" className="empty-cell">No records available for this {terms.learner.toLowerCase()}.</td></tr>}</tbody></table></div></section></div>
}
