import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
const TYPES=[["FACULTY_ASSIGNMENT","Teaching Assignment"],["ADVISOR_ASSIGNMENT","Advisor Assignment"]];
export default function StaffAcademicManagement(){
 const [users,setUsers]=useState([]),[units,setUnits]=useState([]),[rows,setRows]=useState([]),[teacher,setTeacher]=useState(""),[type,setType]=useState("FACULTY_ASSIGNMENT"),[unit,setUnit]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState("");
 async function load(){try{const [u,a,r]=await Promise.all([api.get("/api/v1/users"),api.get("/api/v1/academic-structure"),api.get("/api/v1/academic-assignments")]);setUsers(u.data.filter(x=>x.role==="Teacher"&&x.is_active));setUnits(a.data);setRows(r.data.filter(x=>x.user_role==="Teacher"))}catch(e){setError(e?.response?.data?.detail||"Unable to load teacher assignments.")}}
 useEffect(()=>{load()},[]);
 const allowed=useMemo(()=>units.filter(x=>type==="FACULTY_ASSIGNMENT"?["COURSE","SECTION_BATCH"].includes(x.unit_type):["PROGRAM","SECTION_BATCH"].includes(x.unit_type)),[units,type]);
 const workload=useMemo(()=>users.map(t=>({...t,links:rows.filter(r=>r.user_id===t.id)})),[users,rows]);
 async function assign(e){e.preventDefault();try{setError("");await api.post("/api/v1/academic-assignments",{user_id:Number(teacher),unit_id:Number(unit),assignment_type:type,status:"Active"});setMessage("Teacher assignment saved.");setUnit("");await load()}catch(e){setError(e?.response?.data?.detail||"Unable to save teacher assignment.")}}
 async function remove(id){if(!window.confirm("Remove this teacher assignment?"))return;try{await api.delete("/api/v1/academic-assignments/"+id);setMessage("Teacher assignment removed.");await load()}catch(e){setError(e?.response?.data?.detail||"Unable to remove assignment.")}}
 return <div className="workspace-page"><div className="page-heading"><div><span className="eyebrow">Staff Academic Management</span><h1>Teacher Assignments</h1><p>Assign teachers to courses, sections, programs and advisor responsibilities.</p></div></div>{error&&<div className="error-banner">{error}</div>}{message&&<div className="success-banner">{message}</div>}
 <section className="kpi-grid"><div className="kpi-card"><small>Active Teachers</small><strong>{users.length}</strong></div><div className="kpi-card"><small>Academic Links</small><strong>{rows.length}</strong></div><div className="kpi-card"><small>Unassigned Teachers</small><strong>{workload.filter(x=>x.links.length===0).length}</strong></div><div className="kpi-card"><small>Advisor Links</small><strong>{rows.filter(x=>x.assignment_type==="ADVISOR_ASSIGNMENT").length}</strong></div></section>
 <section className="panel"><div className="panel-title"><b>Create Teacher Assignment</b><span>Institution Admin</span></div><form className="setup-form" onSubmit={assign}><label>Teacher<select required value={teacher} onChange={e=>setTeacher(e.target.value)}><option value="">Select teacher</option>{users.map(x=><option key={x.id} value={x.id}>{x.name} — {x.email}</option>)}</select></label><label>Responsibility<select value={type} onChange={e=>{setType(e.target.value);setUnit("")}}>{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Academic Unit<select required value={unit} onChange={e=>setUnit(e.target.value)}><option value="">Select academic unit</option>{allowed.map(x=><option key={x.id} value={x.id}>{x.name} — {x.unit_type.replaceAll("_"," ")}</option>)}</select></label><button className="primary">Assign Teacher</button></form></section>
 <section className="panel"><div className="panel-title"><b>Teacher Workload</b><span>{workload.length} teachers</span></div><div className="table-scroll"><table><thead><tr><th>Teacher</th><th>Teaching / Advisor Links</th><th>Workload</th></tr></thead><tbody>{workload.map(t=><tr key={t.id}><td><strong>{t.name}</strong><br/><small>{t.email}</small></td><td>{t.links.length?t.links.map(r=><div key={r.id}>{r.unit_name} · {r.assignment_type.replaceAll("_"," ")} <button className="table-action danger" onClick={()=>remove(r.id)}>Remove</button></div>):"Not assigned"}</td><td>{t.links.length} assignment{t.links.length===1?"":"s"}</td></tr>)}</tbody></table></div></section></div>
}