import React,{useEffect,useMemo,useState} from "react";
import {api} from "../api";
export default function StudentEnrollment(){
 const [units,setUnits]=useState([]),[users,setUsers]=useState([]),[students,setStudents]=useState([]),[query,setQuery]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[historyStudent,setHistoryStudent]=useState(null),[history,setHistory]=useState([]),[historyLoading,setHistoryLoading]=useState(false);
 const [form,setForm]=useState({name:"",email:"",password:"",campus_id:1,program_unit_id:"",section_unit_id:"",course_unit_ids:[],parent_user_id:"",relationship:"Guardian"});
 const loadStudents=()=>api.get("/api/v1/admissions/students").then(r=>setStudents(r.data));
 useEffect(()=>{Promise.all([api.get("/api/v1/academic-structure"),api.get("/api/v1/users"),api.get("/api/v1/admissions/students")]).then(([a,u,s])=>{setUnits(a.data);setUsers(u.data);setStudents(s.data)}).catch(e=>setError(e?.response?.data?.detail||"Unable to load enrollment data."))},[]);
 const programs=useMemo(()=>units.filter(x=>["PROGRAM","ACADEMIC_PERIOD"].includes(x.unit_type)),[units]),sections=useMemo(()=>units.filter(x=>x.unit_type==="SECTION_BATCH"),[units]),courses=useMemo(()=>units.filter(x=>x.unit_type==="COURSE"),[units]),parents=useMemo(()=>users.filter(x=>x.role==="Parent / Guardian"&&x.is_active),[users]);
 async function submit(e){e.preventDefault();try{setSaving(true);setError("");const payload={...form,campus_id:Number(form.campus_id),program_unit_id:Number(form.program_unit_id),section_unit_id:form.section_unit_id?Number(form.section_unit_id):null,parent_user_id:form.parent_user_id?Number(form.parent_user_id):null,course_unit_ids:form.course_unit_ids.map(Number)};const r=await api.post("/api/v1/admissions/enroll-student",payload);setMessage(r.data.name+" enrolled successfully.");loadStudents();setForm({name:"",email:"",password:"",campus_id:1,program_unit_id:"",section_unit_id:"",course_unit_ids:[],parent_user_id:"",relationship:"Guardian"})}catch(e){setError(e?.response?.data?.detail||"Unable to enroll student.")}finally{setSaving(false)}}
 const filtered=students.filter(x=>(x.name+" "+x.email+" "+x.status).toLowerCase().includes(query.toLowerCase()));
 async function changeSection(id,section_unit_id){try{await api.patch("/api/v1/admissions/students/"+id,{section_unit_id:Number(section_unit_id)});setMessage("Section updated.");loadStudents()}catch(e){setError(e?.response?.data?.detail||"Unable to update section.")}}
 async function viewHistory(student){try{setHistoryStudent(student);setHistoryLoading(true);setError("");const r=await api.get("/api/v1/admissions/students/"+student.id+"/history");setHistory(r.data)}catch(e){setError(e?.response?.data?.detail||"Unable to load enrollment history.");setHistory([])}finally{setHistoryLoading(false)}}
 async function changeStatus(id,status){if(status==="Withdrawn"&&!window.confirm("Withdraw this student? The account will become inactive."))return;try{await api.patch("/api/v1/admissions/students/"+id,{status});setMessage("Enrollment status updated.");loadStudents()}catch(e){setError(e?.response?.data?.detail||"Unable to update status.")}}
 return <div className="workspace-page"><div className="page-heading"><div><span className="eyebrow">Admissions</span><h1>Student Enrollment</h1><p>Create the student account and academic enrollment in one workflow.</p></div></div>{error&&<div className="error-banner">{error}</div>}{message&&<div className="success-banner">{message}</div>}
 <section className="panel"><form className="setup-form" onSubmit={submit}><label>Student Name<input required value={form.name} onChange={e=>setForm(x=>({...x,name:e.target.value}))}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm(x=>({...x,email:e.target.value}))}/></label><label>Temporary Password<input required type="password" minLength="8" value={form.password} onChange={e=>setForm(x=>({...x,password:e.target.value}))}/></label><label>Campus ID<input required type="number" min="1" value={form.campus_id} onChange={e=>setForm(x=>({...x,campus_id:e.target.value}))}/></label>
 <label>Program / Academic Period<select required value={form.program_unit_id} onChange={e=>setForm(x=>({...x,program_unit_id:e.target.value}))}><option value="">Select</option>{programs.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Section / Batch<select value={form.section_unit_id} onChange={e=>setForm(x=>({...x,section_unit_id:e.target.value}))}><option value="">Optional</option>{sections.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 <label>Courses<select multiple value={form.course_unit_ids} onChange={e=>setForm(x=>({...x,course_unit_ids:Array.from(e.target.selectedOptions,o=>o.value)}))}>{courses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><small>Use Ctrl/Cmd to select multiple courses.</small></label><label>Parent / Guardian<select value={form.parent_user_id} onChange={e=>setForm(x=>({...x,parent_user_id:e.target.value}))}><option value="">Link later</option>{parents.map(x=><option key={x.id} value={x.id}>{x.name} — {x.email}</option>)}</select></label><label>Relationship<input value={form.relationship} onChange={e=>setForm(x=>({...x,relationship:e.target.value}))}/></label><button className="primary" disabled={saving}>{saving?"Enrolling...":"Enroll Student"}</button></form></section><section className="panel"><div className="panel-title"><b>Enrolled Students</b><span>{students.length} records</span></div><input className="search-input" placeholder="Search student" value={query} onChange={e=>setQuery(e.target.value)}/><div className="table-scroll"><table><thead><tr><th>Student</th><th>Academic Assignment</th><th>Section / Batch</th><th>Status</th><th>History</th></tr></thead><tbody>{filtered.length?filtered.map(s=><tr key={s.id}><td>{s.name}<br/><small>{s.email}</small></td><td>{s.assignments.filter(a=>a.assignment_type!=="SECTION_ASSIGNMENT").map(a=><div key={a.id}>{a.unit_name} <small>({a.assignment_type.replaceAll("_"," ")})</small></div>)}</td><td><select value={s.assignments.find(a=>a.assignment_type==="SECTION_ASSIGNMENT")?.unit_id||""} onChange={e=>e.target.value&&changeSection(s.id,e.target.value)}><option value="">Not assigned</option>{sections.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></td><td><select value={s.status} onChange={e=>changeStatus(s.id,e.target.value)}><option>Active</option><option>Withdrawn</option></select></td><td><button className="table-action" onClick={()=>viewHistory(s)}>View History</button></td></tr>):<tr><td colSpan="5" className="empty-cell">No students found.</td></tr>}</tbody></table></div></section>
 {historyStudent&&<section className="panel"><div className="panel-title"><b>Enrollment History — {historyStudent.name}</b><button className="table-action" onClick={()=>{setHistoryStudent(null);setHistory([])}}>Close</button></div>
 {historyLoading?<p>Loading history...</p>:history.length?<div className="table-scroll"><table><thead><tr><th>Date / Time</th><th>Event</th><th>From</th><th>To</th><th>Changed By</th><th>Details</th></tr></thead><tbody>{history.map(h=><tr key={h.id}><td>{new Date(h.created_at).toLocaleString()}</td><td>{h.event_type.replaceAll("_"," ")}</td><td>{h.from_unit||"—"}</td><td>{h.to_unit||"—"}</td><td>{h.actor}</td><td>{h.details||"—"}</td></tr>)}</tbody></table></div>:<div className="empty-cell">No enrollment history recorded yet.</div>}</section>}
 </div>;
}
