import React,{useEffect,useState} from "react"; import {api} from "../api";
export default function TeacherSessions({ui,mode}){
 const [units,setUnits]=useState([]),[sessions,setSessions]=useState([]),[unit,setUnit]=useState(""),[title,setTitle]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[room,setRoom]=useState(""),[selected,setSelected]=useState(null),[students,setStudents]=useState([]),[err,setErr]=useState("");
 const load=()=>Promise.all([api.get("/api/v1/my-academics"),api.get("/api/v1/class-sessions")]).then(([u,s])=>{setUnits(u.data);setSessions(s.data);if(!unit&&u.data[0])setUnit(String(u.data[0].unit_id));setErr("")}).catch(e=>setErr(e?.response?.data?.detail||"Unable to load sessions."));
 useEffect(()=>{load()},[]);
 async function create(){try{await api.post("/api/v1/class-sessions",{unit_id:Number(unit),title,starts_at:start,ends_at:end,room});setTitle("");setStart("");setEnd("");setRoom("");load()}catch(e){setErr(e?.response?.data?.detail||"Unable to create class session.")}}
 async function openAttendance(id){try{setSelected(id);const r=await api.get("/api/v1/class-sessions/"+id+"/attendance");setStudents(r.data)}catch(e){setErr(e?.response?.data?.detail||"Unable to load attendance.")}}
 async function mark(student,status,currentNote=""){const note=prompt("Attendance note (optional)",currentNote||"");if(note===null)return;try{await api.put("/api/v1/class-sessions/"+selected+"/attendance",{student_user_id:student,status,note});openAttendance(selected)}catch(e){setErr(e?.response?.data?.detail||"Unable to mark attendance.")}} async function editSession(s){const title=prompt("Session title",s.title);if(title===null)return;const starts=prompt("Starts (YYYY-MM-DDTHH:MM)",String(s.starts_at).slice(0,16));if(starts===null)return;const ends=prompt("Ends (YYYY-MM-DDTHH:MM)",String(s.ends_at).slice(0,16));if(ends===null)return;const room=prompt("Room",s.room||"");if(room===null)return;const status=prompt("Status: SCHEDULED / COMPLETED / CANCELLED",s.status||"SCHEDULED");if(!status)return;try{await api.put("/api/v1/class-sessions/"+s.id,{title,starts_at:starts,ends_at:ends,room,status});load()}catch(e){setErr(e?.response?.data?.detail||"Unable to update class session.")}}
 return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Faculty</span><h1>{mode}</h1><p>Scheduled sessions and attendance are limited to your assigned academic units.</p></div></section>{err&&<div className="error">{err}</div>}<div className="setup-grid">{mode==="Timetable"&&<section className="panel"><div className="panel-title"><b>Schedule Class</b><span>Timetable</span></div><div className="setup-form"><label>Course / Section<select value={unit} onChange={e=>setUnit(e.target.value)}>{units.map(x=><option key={x.assignment_id} value={x.unit_id}>{x.name}</option>)}</select></label><label>Session<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Starts<input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Ends<input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Room<input value={room} onChange={e=>setRoom(e.target.value)}/></label></div><button className="primary" disabled={!unit||!title||!start||!end} onClick={create}>Schedule Session</button></section>}<section className="panel"><div className="panel-title"><b>Sessions</b><span>{sessions.length}</span></div><div className="session-list">{sessions.map(s=><button key={s.id} className={selected===s.id?"session-row selected":"session-row"} onClick={()=>openAttendance(s.id)}><b>{s.title}</b><span>{new Date(s.starts_at).toLocaleString()} · {s.room||"Room TBA"} · {s.status}</span><span className="table-action" onClick={e=>{e.stopPropagation();editSession(s)}}>Update</span></button>)}</div></section></div>{selected&&<section className="panel structure-table"><div className="panel-title"><b>Attendance Register</b><span>{students.length} students</span></div><div className="table-scroll"><table><thead><tr><th>Student</th><th>Status</th><th>Note</th><th>Mark</th></tr></thead><tbody>{students.map(s=><tr key={s.student_user_id}><td><b>{s.student_name}</b></td><td>{s.status}</td><td>{s.note||"—"}</td><td className="attendance-actions">{["PRESENT","ABSENT","LATE","EXCUSED"].map(v=><button key={v} onClick={()=>mark(s.student_user_id,v,s.note)}>{v}</button>)}</td></tr>)}</tbody></table></div></section>}</div>
}