import React,{useEffect,useState} from "react"; import {api} from "../api";
export default function TeacherResults({ui}){
 const [exams,setExams]=useState([]),[exam,setExam]=useState(""),[students,setStudents]=useState([]),[values,setValues]=useState({}),[complete,setComplete]=useState(false),[published,setPublished]=useState(false),[err,setErr]=useState(""),[msg,setMsg]=useState("");
 const loadExams=()=>api.get("/api/v1/academic-work",{params:{work_type:"EXAM"}}).then(r=>{setExams(r.data);if(!exam&&r.data[0])setExam(String(r.data[0].id))}).catch(e=>setErr(e?.response?.data?.detail||"Unable to load exams."));
 const loadRegister=()=>{if(!exam){setStudents([]);return} api.get("/api/v1/exams/"+exam+"/results").then(r=>{setStudents(r.data.students||[]);setComplete(!!r.data.complete);setPublished(!!r.data.published);const next={};(r.data.students||[]).forEach(s=>{next[s.student_id]={marks:s.marks??"",remarks:s.remarks||""}});setValues(next);setErr("")}).catch(e=>setErr(e?.response?.data?.detail||"Unable to load marks register."))};
 useEffect(()=>{loadExams()},[]);
 useEffect(()=>{loadRegister()},[exam]);
 const set=(id,k,v)=>setValues(x=>({...x,[id]:{...(x[id]||{}),[k]:v}}));
 async function save(s){try{const v=values[s.student_id]||{};const numeric=Number(v.marks);if(v.marks===""||!Number.isFinite(numeric)||numeric<0||(current?.max_marks!=null&&numeric>Number(current.max_marks))){setErr("Marks must be between 0 and the exam maximum.");return}const r=await api.put("/api/v1/exams/"+exam+"/results",{student_user_id:s.student_id,marks:numeric,remarks:v.remarks||""});setMsg("Marks saved: "+r.data.percentage+"% · "+r.data.grade+" · "+r.data.result_status);setErr("");loadRegister()}catch(e){setErr(e?.response?.data?.detail||"Unable to save marks.")}}
 async function publish(){try{const r=await api.post("/api/v1/exams/"+exam+"/publish");setMsg(r.data.published+" results published to students.");setErr("");loadRegister()}catch(e){setErr(e?.response?.data?.detail||"Unable to publish results.")}}
 const current=exams.find(x=>String(x.id)===exam);
 return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Faculty</span><h1>Marks & Results</h1><p>Enter marks for every enrolled student. Grades are calculated from the institution grading scheme and published results are locked.</p></div></section>
 <section className="panel"><div className="setup-form"><label>Exam<select value={exam} onChange={e=>setExam(e.target.value)}><option value="">Select exam</option>{exams.map(x=><option key={x.id} value={x.id}>{x.title} · Max {x.max_marks}</option>)}</select></label></div>{err&&<div className="error">{err}</div>}{msg&&<div className="success-message">{msg}</div>}</section>
 <section className="panel structure-table"><div className="panel-title"><div><b>{current?.title||"Exam"} Marks Register</b><small>{published?"Published & locked":complete?"Ready to publish":"Complete all student marks before publishing"}</small></div><button className="primary" disabled={!exam||!students.length||!complete||published} onClick={publish}>{published?"Published":"Publish Results"}</button></div><div className="table-scroll"><table><thead><tr><th>Student</th><th>Marks</th><th>%</th><th>Grade</th><th>Result</th><th>Remarks</th><th>Action</th></tr></thead><tbody>{students.length?students.map(s=><tr key={s.student_id}><td><b>{s.student_name}</b></td><td><input className="marks-input" type="number" min="0" max={current?.max_marks} disabled={s.published} value={values[s.student_id]?.marks??""} onChange={e=>set(s.student_id,"marks",e.target.value)}/></td><td>{s.percentage??"—"}</td><td>{s.grade||"—"}</td><td>{s.result_status||"—"}</td><td><input disabled={s.published} value={values[s.student_id]?.remarks??""} onChange={e=>set(s.student_id,"remarks",e.target.value)}/></td><td><button className="table-action" disabled={s.published||values[s.student_id]?.marks==null||values[s.student_id]?.marks===""} onClick={()=>save(s)}>{s.published?"Locked":"Save Marks"}</button></td></tr>):<tr><td colSpan="7" className="empty-cell">No enrolled students for this exam.</td></tr>}</tbody></table></div></section></div>
}