import React,{useEffect,useState} from "react";
import {api} from "../api";
export default function TeacherCommunication({ui}){
 const [recipients,setRecipients]=useState([]),[rows,setRows]=useState([]),[recipient,setRecipient]=useState(""),[subject,setSubject]=useState(""),[body,setBody]=useState(""),[err,setErr]=useState(""),[msg,setMsg]=useState("");
 const load=()=>Promise.all([api.get("/api/v1/teacher/communication/recipients"),api.get("/api/v1/teacher/communication")]).then(([r,m])=>{setRecipients(r.data||[]);setRows(m.data||[]);setErr("")}).catch(e=>setErr(e?.response?.data?.detail||"Unable to load communication."));
 useEffect(()=>{load()},[]);
 const selected=recipients.find((x,i)=>String(i)===recipient);
 async function send(){if(!selected)return;try{await api.post("/api/v1/teacher/communication",{recipient_user_id:selected.user_id,student_user_id:selected.student_user_id,subject:subject.trim(),body:body.trim()});setSubject("");setBody("");setMsg("Message sent.");load()}catch(e){setErr(e?.response?.data?.detail||"Unable to send message.")}}
 return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Faculty</span><h1>Communication</h1><p>Send academic communication only to students in your assigned classes or their linked guardians.</p></div></section>{err&&<div className="error">{err}</div>}{msg&&<div className="success">{msg}</div>}
 <div className="setup-grid"><section className="panel"><div className="panel-title"><b>New Message</b><span>Teacher scoped</span></div><div className="setup-form"><label>Recipient<select value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">Select recipient</option>{recipients.map((x,i)=><option key={x.user_id+"-"+x.student_user_id+"-"+i} value={i}>{x.name} — {x.role}{x.student_name?" ("+x.student_name+")":""}</option>)}</select></label><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Message<textarea value={body} onChange={e=>setBody(e.target.value)}/></label></div><button className="primary" disabled={!selected||!subject.trim()||!body.trim()} onClick={send}>Send Message</button></section>
 <section className="panel structure-table"><div className="panel-title"><b>Sent Messages</b><span>{rows.length}</span></div><div className="table-scroll"><table><thead><tr><th>Recipient</th><th>Student Context</th><th>Subject</th><th>Status</th><th>Sent</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><b>{x.recipient}</b><div className="muted">{x.recipient_role}</div></td><td>{x.student_name||"—"}</td><td>{x.subject}</td><td>{x.status}</td><td>{new Date(x.created_at).toLocaleString()}</td></tr>):<tr><td colSpan="5" className="empty-cell">No messages sent yet.</td></tr>}</tbody></table></div></section></div></div>
}