import React,{useEffect,useState} from "react"; import {api} from "../api";
export default function TeacherResults({ui}){
 const [exams,setExams]=useState([]),[exam,setExam]=useState(""),[students,setStudents]=useState([]),[values,setValues]=useState({}),[err,setErr]=useState(""),[msg,setMsg]=useState("");
 const loadExams=()=>api.get("/api/v1/academic-work",{params:{work_type:"EXAM"}}).then(r=>{setExams(r.data);if(!exam&&r.data[0])setExam(String(r.data[0].id))}).catch(e=>setErr(e?.response?.data?.detail||"Unable to load exams."));
 useEffect(()=>{loadExams()},[]);
 useEffect(()=>{if(!exam){setStudents([]);return} api.get("/api/v1/academic-work/"+exam+"/submissions").then(r=>setStudents(r.data)).catch(e=>setErr(e?.response?.data?.detail||"Unable to load students."))},[exam]);
 const set=(id,k,v)=>setValues(x=>({...x,[id]:{...(x[id]||{}),[k]:v}}));
 async function save(s){try{const v=values[s.student_id]||{};await api.put("/api/v1/exams/"+exam+"/results",{student_user_id:s.student_id,marks:Number(v.marks),remarks:v.remarks||""});setMsg("Marks saved and grade calculated.");setErr("")}catch(e){setErr(e?.response?.data?.detail||"Unable to save marks.")}}
 async function publish(){try{const r=await api.post("/api/v1/exams/"+exam+"/publish");setMsg(r.data.published+" results published to students.");setErr("")}catch(e){setErr(e?.response?.data?.detail||"Unable to publish results.")}}
 const current=exams.find(x=>String(x.id)===exam);
 return <div><section className="module-context"><div><span className="eyebrow">{ui.label} • Faculty</span><h1>Marks & Results</h1><p>Enter marks for enrolled students. Grades are calculated from the institution grading scheme.</p></div></section>
 <section className="panel"><div className="setup-form"><label>Exam<select value={exam} onChange={e=>setExam(e.target.value)}><option value="">Select exam</option>{exams.map(x=><option key={x.id} value={x.id}>{x.title} · Max {x.max_marks}</option>)}</select></label></div>{err&&<div className="error">{err}</div>}{msg&&<div className="success-message">{msg}</div>}</section>
 <section className="panel structure-table"><div className="panel-title"><b>{current?.title||"Exam"} Marks Register</b><button className="primary" disabled={!exam||!students.length} onClick={publish}>Publish Results</button></div><div className="table-scroll"><table><thead><tr><th>Student</th><th>Marks</th><th>Remarks</th><th>Action</th></tr></thead><tbody>{students.length?students.map(s=><tr key={s.student_id}><td><b>{s.student_name}</b></td><td><input className="marks-input" type="number" min="0" max={current?.max_marks} value={values[s.student_id]?.marks??""} onChange={e=>set(s.student_id,"marks",e.target.value)}/></td><td><input value={values[s.student_id]?.remarks??""} onChange={e=>set(s.student_id,"remarks",e.target.value)}/></td><td><button className="table-action" disabled={values[s.student_id]?.marks==null||values[s.student_id]?.marks===""} onClick={()=>save(s)}>Save Marks</button></td></tr>):<tr><td colSpan="4" className="empty-cell">No enrolled students for this exam.</td></tr>}</tbody></table></div></section></div>
}